### ISSUE TITLE
Feature: 支持 Telegram 的 GIF 的接收与发送

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#1006]
### Describe the problem related to the feature request

例如在图片元素中 `type=gif`

### Describe the solution you'd like

无法接收与发送 GIF

**Comment by Anillc** [comment]
我印象中是可以发的，现在发不了吗

收的话可能有些麻烦，telegram 是以视频的形式传输的 gif

**Comment by idanran** [comment]
> 我印象中是可以发的，现在发不了吗
> 
> 收的话可能有些麻烦，telegram 是以视频的形式传输的 gif

我不知道该怎么发，默认是以图片的形式发送，无法正常显示。

**Comment by shigma** [comment]
我印象中也是可以发的，安妮写的实现，可能被我改炸了.jpg

**Comment by KuroshioDev** [comment]
forward是可以发的

**Comment by idanran** [comment]
```
2023-03-12 12:13:36 [W] telegram get file error TypeError [ERR_INVALID_URL]: Invalid URL     at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)     at new NodeError (node:internal/errors:399:5)     at new URL (node:internal/url:588:13) at Quester.file (C:\x\node_modules\cordis-axios\src\index.ts:84:23) at Quester.file (C:\x\node_modules\@satorijs\satori\src\axios.ts:28:18) at TelegramBot.$getFile (C:\x\node_modules\@satorijs\adapter-telegram\src\bot.ts:257:30) at TelegramBot.$getFileFromPath (C:\x\node_modules\@satorijs\adapter-telegram\src\bot.ts:274:39) at TelegramBot.$getFileFromId (C:\x\node_modules\@satorijs\adapter-telegram\src\b..
```
发送后终端提示这个

**Comment by idanran** [comment]
包含 GIF 的消息元素：
```
Element {
    type: 'image',
    attrs: {
      file: '02fc64ebbb991d951cdf49008edaab01.image',
      subType: '7',
      url: 'https://gchat.qpic.cn/gchatpic_new/2098923471/654259434-2772636126-02FC64EBBB991D951CDF49008EDAAB01/0?term=3&is_origin=0'
    },
    children: []
  }
```
发送后的显示：
![qq_pic_merged_1678595596342](https://user-images.githubusercontent.com/96647698/224524553-f9fe30d1-efa4-4f14-99f5-5d3e939f20c2.jpg)

**Comment by idanran** [comment]
使用 ctx.http.file 访问以上链接，得到：
```
{
  mime: 'image/gif',
  filename: '0',
  data: <Buffer 47 49 46 38 39 61 26 01 26 01 f6 00 00 07 03 03 14 07 01 18 10 08 25 14 0a 21 1b 1b 30 22 15 34 2c 28 42 1b 09 49 2c 15 5d 35 17 40 3d 3d 4a 38 2e 6f ... 531840 more bytes>
}
```

应该能证明 tg 适配器中 appendAsset 函数里的
```
if (element.type === 'image') {
    assetType = mime === 'image/gif' ? 'animation' : 'photo'
} else if (element.type === 'file') {
    assetType = 'document'
} else {
    assetType = element.type as any
}
```
是能正常工作的

**Comment by idanran** [comment]
我现在有点怀疑是 filename 导致的问题

**Comment by idanran** [comment]
通过修改 node_modules 里的文件，已确定是 filename 的问题。当前 ctx.http.file 获取到的 filename 为 0，需要指定正确的后缀才能在客户端正常显示。
