### ISSUE TITLE
Bug: Forward转发TG图片时，TG适配器报无法下载图片

### ISSUE THREAD

**Issue by KuroshioDev** [koishijs/koishi#1024]
### Describe the bug

Forward转发TG图片（.jpg格式）时，TG适配器报无法下载图片

```
2023-03-09 21:31:15 [W] telegram get file error TypeError [ERR_INVALID_URL]: Invalid URL     at new NodeError (node:internal/errors:372:5)     at URL.onParseError (node:internal/url:563:9)     at new URL (node:internal/url:643:5) at Quester.file (/home/admin/app/kuroshio-bot/node_modules/cordis-axios/lib/index.js:89:23) at Quester.file (/home/admin/app/kuroshio-bot/node_modules/@satorijs/satori/lib/index.js:106:18) at TelegramBot.$getFile (/home/admin/app/kuroshio-bot/node_modules/@satorijs/adapter-telegram/lib/index.js:715:30) at TelegramBot.$getFileFromPath (/home/admin/app/kuroshio-bot/node_modules/@satorijs/adapter-telegram/lib/index.js:730:39) at TelegramBot.$getFileFromId (/home/admin/app/kuroshio-bot/node_modules/@satorijs/adapter-telegram/lib/index.js:721:25)     at processTicksAndRejections (node:internal/process/task_queues:96:5) at async TelegramBot.adaptMessage (/home/admin/app/kurosh...
2023-03-09 21:31:15 [W] gocqhttp 警告: 频道 93248811658287152 图片上传失败: image type error: application/octet-stream
```

### Steps to reproduce

1.安装forward插件
2.接入tg频道
3.设置tg频道转发QQ频道规则(不清楚其他平台有没这个问题)
4.往tg频道发送图片

### Expected behavior

能转发图片

### Versions

System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz

Binaries:
    Node: 17.9.1
    Yarn: 1.22.19

Koishi:
    Core: 4.11.9
    Console: 5.5.4

**Comment by shigma** [comment]
合着你下午在群里说 Koishi 坏了，大闹半天都没有提供最关键的信息：你的图片不是正常发送的，而是 tg 转来的。

而且你说 forward 的时候没有人知道你在说 forward 插件，所有人都认为你说的是 `<message forward>`。KBD 还专门截了合并转发的图片，你也不指出来因为表达有误让大家误解。

在解决这个问题之前，我想让你对上述行为进行合理解释：你是故意来浪费大家时间的吗？

**Comment by MaikoTan** [comment]
What's going on?

**Comment by shigma** [comment]
额这个问题还没解决吧

**Comment by shigma** [comment]
你还能复现此问题的话就留着别关，我没说不解决。
