### ISSUE TITLE
Bug: 沙盒无法正常更改用户权限等级

### ISSUE THREAD

**Issue by FlandreCirno** [koishijs/koishi#1042]
### Describe the bug

在更新沙盒用户等级后，用户等级无法正确更新，刷新页面后权限会恢复到1

### Steps to reproduce

创建模板项目，进入沙盒，创建用户，点击加号修改用户权限等级

### Expected behavior

用户等级应当正确更改、保存且反应在可以使用更高级的指令

### Versions

OS: Windows 10
Platform: Sandbox
Node version: 18.15.0
Koishi version: 4.12.1

### Additional context

控制台报错信息
client.js:1 Uncaught (in promise) Error: UNIQUE constraint failed: binding.pid, binding.platform
    at f.handleError (E:\Workspace\Koishi\Test\test\node_modules\@minatojs\sql.js\dist\sql-wasm.js:91:290)
    at c.step (E:\Workspace\Koishi\Test\test\node_modules\@minatojs\sql.js\dist\sql-wasm.js:81:394)
    at c.run (E:\Workspace\Koishi\Test\test\node_modules\@minatojs\sql.js\dist\sql-wasm.js:84:116)
    at E:\Workspace\Koishi\Test\test\node_modules\@minatojs\driver-sqlite\lib\index.js:365:80
    at #exec (E:\Workspace\Koishi\Test\test\node_modules\@minatojs\driver-sqlite\lib\index.js:339:20)
    at #run (E:\Workspace\Koishi\Test\test\node_modules\@minatojs\driver-sqlite\lib\index.js:365:41)
    at #create (E:\Workspace\Koishi\Test\test\node_modules\@minatojs\driver-sqlite\lib\index.js:394:46)
    at SQLiteDriver.create (E:\Workspace\Koishi\Test\test\node_modules\@minatojs\driver-sqlite\lib\index.js:302:62)
    at Executable.execute (E:\Workspace\Koishi\Test\test\node_modules\@minatojs\core\lib\index.cjs:384:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by shigma** [comment]
已定位问题。
