### ISSUE TITLE
Bug?: 4.12.7升级到4.12.9就无法启动了

### ISSUE THREAD

**Issue by k99k5** [koishijs/koishi#1106]
### Describe the bug

2023-06-05 16:28:59 [W] app TypeError: Cannot read properties of undefined (reading 'refresh')
                            at NodeConsole.addEntry (/koishi/node_modules/@koishijs/plugin-console/lib/shared/index.js:189:16)
                            at new CommandProvider (/koishi/node_modules/@koishijs/plugin-commands/lib/index.js:59:17)
                            at MainScope.apply (/koishi/node_modules/cordis/lib/index.cjs:417:26)
                            at MainScope.start (/koishi/node_modules/cordis/lib/index.cjs:475:12)
                            at Object. (/koishi/node_modules/cordis/lib/index.cjs:284:12)
                            at Lifecycle.emit (/koishi/node_modules/cordis/lib/index.cjs:100:16)
                            at Context.emit (/koishi/node_modules/cordis/lib/index.cjs:621:31)
                            at Context.set (/koishi/node_modules/cordis/lib/index.cjs:673:16)
                            at /koishi/node_modules/@koishijs/core/node_modules/cordis/lib/index.cjs:713:17
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Steps to reproduce

从4.12.7升级到4.12.9就炸了（）

### Expected behavior

正常启动

### Versions

- OS: linux
- Koishi version: 4.12.9
- plugin-console: 5.8.4

**Comment by shigma** [comment]
你没有同时升级所有依赖，导致部分依赖版本要求没有满足。如果你不想考虑依赖版本问题，请将所有插件同时升级到最新版本。

**Comment by k99k5** [comment]
> 你没有同时升级所有依赖，导致部分依赖版本要求没有满足。如果你不想考虑依赖版本问题，请将所有插件同时升级到最新版本。

了解了，刚刚全部更新了，已经启动正常了。
但是插件配置页面的入口不见了
