### ISSUE TITLE
Bug(cordis): 插件异步加载当`immediate=true`且存在复杂依赖时有概率多次加载

### ISSUE THREAD

**Issue by Hieuzest** [koishijs/koishi#1130]
### Describe the bug

现在有新建立的Service `foo` 和Plugin `bar`
```
foo::using = ['database']
foo::immediate = true
bar::using = ['database', 'foo']
```
使用yarn dev或yarn start运行，bar被加载两次
```
2023-06-30 05:05:41 [I] app server listening at http://127.0.0.1:5140
Foo service initializing.
Bar service initializing.
Bar service initializing.
```

特别的，当bar也为Service且又有 `bar::immediate = true`
则有如下报错：
```
2023-06-30 05:06:42 [I] app server listening at http://127.0.0.1:5140
Foo service initializing.
Bar service initializing.
Bar service initializing.
2023-06-30 05:06:42 [W] app Error: service bar has been registered
                            at Context.set (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\cordis\src\context.ts:129:17)
                            at MainScope.MainScope.apply (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\cordis\src\scope.ts:303:21)
                            at MainScope.start (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\cordis\src\scope.ts:326:12)
                            at Object.<anonymous> (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\cordis\src\scope.ts:121:12)
                            at Lifecycle.emit (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\cordis\src\events.ts:98:16)
                            at Context.emit (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\cordis\src\context.ts:81:30)
                            at Context.set (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\cordis\src\context.ts:140:16)
                            at <anonymous> (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@koishijs\core\src\database.ts:238:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Promise.all (index 19)
2023-06-30 05:06:42 [W] app Error: service bar has been registered
                            at Context.set (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\cordis\src\context.ts:129:17)
                            at <anonymous> (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\cordis\src\service.ts:22:15)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-06-30 05:06:42 [W] app MongoNotConnectedError: MongoClient must be connected to perform this operation
                            at getTopology (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\utils.ts:299:9)
                            at BulkOperationBase (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\bulk\common.ts:989:33)
                            at OrderedBulkOperation (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\bulk\ordered.ts:13:5)
                            at Collection.initializeOrderedBulkOp (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\collection.ts:1625:12)
                            at MongoDriver._createFields (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\src\index.ts:126:23)
                            at MongoDriver.prepare (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\src\index.ts:183:12)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at DatabaseService.prepare (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\core\src\driver.ts:92:5)
2023-06-30 05:06:42 [W] app MongoPoolClosedError: Attempted to check out a connection from closed connection pool
                            at ConnectionPool.processWaitQueue (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\cmap\connection_pool.ts:757:37)
                            at ConnectionPool.close (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\cmap\connection_pool.ts:509:10)
                            at Server.destroy (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\server.ts:264:17)
                            at destroyServer (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:773:10)
                            at node:internal/util:375:7
                            at new Promise (<anonymous>)
                            at destroyServer (node:internal/util:361:12)
                            at <anonymous> (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:506:38)
                            at Function.from (<anonymous>)
                            at Topology.close (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:505:36)
2023-06-30 05:06:42 [W] app MongoPoolClosedError: Attempted to check out a connection from closed connection pool
                            at ConnectionPool.processWaitQueue (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\cmap\connection_pool.ts:757:37)
                            at ConnectionPool.close (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\cmap\connection_pool.ts:509:10)
                            at Server.destroy (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\server.ts:264:17)
                            at destroyServer (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:773:10)
                            at node:internal/util:375:7
                            at new Promise (<anonymous>)
                            at destroyServer (node:internal/util:361:12)
                            at <anonymous> (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:506:38)
                            at Function.from (<anonymous>)
                            at Topology.close (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:505:36)
2023-06-30 05:06:42 [W] app MongoPoolClosedError: Attempted to check out a connection from closed connection pool
                            at ConnectionPool.processWaitQueue (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\cmap\connection_pool.ts:757:37)
                            at ConnectionPool.close (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\cmap\connection_pool.ts:509:10)
                            at Server.destroy (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\server.ts:264:17)
                            at destroyServer (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:773:10)
                            at node:internal/util:375:7
                            at new Promise (<anonymous>)
                            at destroyServer (node:internal/util:361:12)
                            at <anonymous> (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:506:38)
                            at Function.from (<anonymous>)
                            at Topology.close (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:505:36)
2023-06-30 05:06:42 [W] app MongoPoolClosedError: Attempted to check out a connection from closed connection pool
                            at ConnectionPool.processWaitQueue (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\cmap\connection_pool.ts:757:37)
                            at ConnectionPool.close (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\cmap\connection_pool.ts:509:10)
                            at Server.destroy (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\server.ts:264:17)
                            at destroyServer (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:773:10)
                            at node:internal/util:375:7
                            at new Promise (<anonymous>)
                            at destroyServer (node:internal/util:361:12)
                            at <anonymous> (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:506:38)
                            at Function.from (<anonymous>)
                            at Topology.close (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\sdam\topology.ts:505:36)
2023-06-30 05:06:42 [W] app MongoNotConnectedError: MongoClient must be connected to perform this operation
                            at getTopology (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\utils.ts:299:9)
                            at BulkOperationBase (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\bulk\common.ts:989:33)
                            at OrderedBulkOperation (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\bulk\ordered.ts:13:5)
                            at Collection.initializeOrderedBulkOp (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\collection.ts:1625:12)
                            at MongoDriver._createFields (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\src\index.ts:126:23)
                            at MongoDriver.prepare (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\src\index.ts:183:12)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at DatabaseService.prepare (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\core\src\driver.ts:92:5)
2023-06-30 05:06:42 [W] app MongoNotConnectedError: MongoClient must be connected to perform this operation
                            at getTopology (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\utils.ts:299:9)
                            at BulkOperationBase (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\bulk\common.ts:989:33)
                            at OrderedBulkOperation (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\bulk\ordered.ts:13:5)
                            at Collection.initializeOrderedBulkOp (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\node_modules\mongodb\src\collection.ts:1625:12)
                            at MongoDriver._createFields (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\src\index.ts:126:23)
                            at MongoDriver.prepare (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\driver-mongo\src\index.ts:183:12)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at DatabaseService.prepare (C:\Users\girki\AppData\Roaming\Koishi\Dev\node_modules\@minatojs\core\src\driver.ts:92:5)

```
此时database加载失败

### Steps to reproduce

/

### Expected behavior

/

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by shigma** [comment]
抱歉没太看懂，上最小复现代码吧。

**Comment by Hieuzest** [comment]
总之就是

external/bar/src/index.ts
```
import { Context, Service } from 'koishi'

export class Bar extends Service {
  static using = ['database', 'foo']
  
  constructor(ctx: Context) {
    super(ctx, 'bar')
    
    console.log('Bar service initializing.')
  }
}

export default Bar
```

external/foo/src/index.ts
```
import { Context, Service } from 'koishi'

export class Foo extends Service {
  static using = ['database']
  
  constructor(ctx: Context) {
    super(ctx, 'foo', true)
    
    console.log('Foo service initializing.')
  }
}

export default Foo
```
启用两个插件直接运行就有几率复现


Log
```
Emit internal/service database
On service database CommandProvider
On service database config
On service database SchemaProvider
On service database PackageProvider
On service database ServiceProvider
On service database ConfigWriter
On service database DatabaseProvider
Start DatabaseProvider group
On service database Explorer
On service database LogProvider
On service database Insight
On service database anonymous
On service database anonymous
On service database sandbox
On service database SandboxService
Start SandboxService sandbox
On service database status
On service database EnvInfoProvider
On service database ProfileProvider
On service database Watcher
On service database Foo
Start Foo group
Foo service initializing.
Emit internal/service foo
On service foo CommandProvider
On service foo config
On service foo SchemaProvider
On service foo PackageProvider
On service foo ServiceProvider
On service foo ConfigWriter
On service foo DatabaseProvider
On service foo Explorer
On service foo LogProvider
On service foo Insight
On service foo anonymous
On service foo anonymous
On service foo sandbox
On service foo SandboxService
On service foo status
On service foo EnvInfoProvider
On service foo ProfileProvider
On service foo Watcher
On service foo Foo
On service foo Bar
Start Bar group
Error
    at Function.service (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\context.ts:104:37)
    at Service (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\service.ts:11:30)
    at Bar (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\barrrr\src\index.ts:7:5)
    at MainScope.MainScope.apply (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\scope.ts:302:24)
    at MainScope.start (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\scope.ts:329:12)
    at Object.<anonymous> (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\scope.ts:123:12)
    at Lifecycle.emit (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\events.ts:98:16)
    at Context.emit (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\context.ts:81:30)
    at Context.set (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\context.ts:143:16)
    at MainScope.MainScope.apply (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\scope.ts:305:21)
Bar service initializing.
On service foo DependencyProvider
On service foo RegistryProvider
On service foo MarketProvider
On service database Bar
Start Bar group
Error
    at Function.service (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\context.ts:104:37)
    at Service (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\service.ts:11:30)
    at Bar (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\barrrr\src\index.ts:7:5)
    at MainScope.MainScope.apply (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\scope.ts:302:24)
    at MainScope.start (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\scope.ts:329:12)
    at Object.<anonymous> (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\scope.ts:123:12)
    at Lifecycle.emit (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\events.ts:98:16)
    at Context.emit (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\context.ts:81:30)
    at Context.set (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\context.ts:143:16)
    at <anonymous> (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\koishi\packages\core\src\database.ts:238:11)
Bar service initializing.
On service database DependencyProvider
On service database RegistryProvider
On service database MarketProvider
Emit internal/service console.database
On service console.database CommandProvider
On service console.database config
On service console.database SchemaProvider
On service console.database PackageProvider
On service console.database ServiceProvider
On service console.database ConfigWriter
On service console.database DatabaseProvider
On service console.database Explorer
On service console.database LogProvider
On service console.database Insight
On service console.database anonymous
On service console.database anonymous
On service console.database sandbox
On service console.database SandboxService
On service console.database status
On service console.database EnvInfoProvider
On service console.database ProfileProvider
On service console.database Watcher
On service console.database Foo
On service console.database Bar
On service console.database DependencyProvider
On service console.database RegistryProvider
On service console.database MarketProvider
Emit internal/service console.sandbox
On service console.sandbox CommandProvider
On service console.sandbox config
On service console.sandbox SchemaProvider
On service console.sandbox PackageProvider
On service console.sandbox ServiceProvider
On service console.sandbox ConfigWriter
On service console.sandbox DatabaseProvider
On service console.sandbox Explorer
On service console.sandbox LogProvider
On service console.sandbox Insight
On service console.sandbox anonymous
On service console.sandbox anonymous
On service console.sandbox sandbox
On service console.sandbox SandboxService
On service console.sandbox status
On service console.sandbox EnvInfoProvider
On service console.sandbox ProfileProvider
On service console.sandbox Watcher
On service console.sandbox Foo
On service console.sandbox Bar
On service console.sandbox DependencyProvider
On service console.sandbox RegistryProvider
On service console.sandbox MarketProvider
Emit internal/service bar
On service bar CommandProvider
On service bar config
On service bar SchemaProvider
On service bar PackageProvider
On service bar ServiceProvider
On service bar ConfigWriter
On service bar DatabaseProvider
On service bar Explorer
On service bar LogProvider
On service bar Insight
On service bar anonymous
On service bar anonymous
On service bar sandbox
On service bar SandboxService
On service bar status
On service bar EnvInfoProvider
On service bar ProfileProvider
On service bar Watcher
On service bar Foo
On service bar Bar
On service bar DependencyProvider
On service bar RegistryProvider
On service bar MarketProvider
2023-06-30 10:43:54 [W] app Error: service bar has been registered
                            at Context.set (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\context.ts:131:17)
                            at <anonymous> (c:\Users\girki\AppData\Roaming\Koishi\Dev\external\cordis\src\service.ts:22:15)
Emit internal/service bar
On service bar CommandProvider
On service bar config
On service bar SchemaProvider
On service bar PackageProvider
On service bar ServiceProvider
On service bar ConfigWriter
On service bar DatabaseProvider
On service bar Explorer
On service bar LogProvider
On service bar Insight
On service bar anonymous
On service bar anonymous
On service bar sandbox
On service bar SandboxService
On service bar status
On service bar EnvInfoProvider
On service bar ProfileProvider
On service bar Watcher
On service bar Foo
On service bar Bar
On service bar DependencyProvider
On service bar RegistryProvider
On service bar MarketProvider
```
定位了问题，database的internal/service先触发了foo start,随后foo的internal/service触发了bar start,然后database的internal/service再一次触发了bar start
当foo::immediate=false时，第一次bar start不满足ready因此不产生问题

**Comment by shigma** [comment]
感谢反馈，已修复。
