### ISSUE TITLE
Bug: telegram slash command 无法使用

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1174]
### Describe the bug

原本的 tg 适配器没有对 slash command 做兼容，更新了koishi 及其依赖和适配器后，所有带下划线的指令都无法处理

```
TypeError: Cannot destructure property 'name' of 'session.data.argv' as it is undefined.
                            at _Session.<anonymous> (E:\Project\bot\node_modules\@koishijs\core\src\middleware.ts:87:15)     
                            at _Lifecycle.emit (E:\Project\bot\node_modules\cordis\src\events.ts:98:16)
                            at _Context.emit (E:\Project\bot\node_modules\cordis\src\context.ts:81:30)
                            at _TelegramBot.dispatch (E:\Project\bot\node_modules\@satorijs\core\src\bot.ts:119:20)
                            at handleUpdate (E:\Project\bot\node_modules\@satorijs\adapter-telegram\src\utils.ts:89:7)       
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps to reproduce

如题

### Expected behavior

如题

### Versions

koishi: 4.14.1
adapter-telegram: 3.8.0

**Comment by shigma** [comment]
等明天更新就行了。

**Comment by shigma** [comment]
4.14.2 版本已经支持。
