### ISSUE TITLE
Bug: 插件市场无法访问

### ISSUE THREAD

**Issue by ymy139** [koishijs/koishi#1175]
### Describe the bug

无法使用插件商店（仍需更多数据验证）

---

### Steps to reproduce

- 无法使用插件商店（仍需更多数据验证）
1. 启动koishi并访问后台插件商店

该问题在更换源后仍无法解决（尝试使用了官方源，淘宝源，南大源，浙大源）
查看后台日志发现有10条左右的超时提醒

---

---

### Screenshots

插件市场提示：
![微信图片_20230821132759](https://github.com/koishijs/koishi/assets/117415378/3fbc54e2-e483-4cfb-9177-8cadf27772f5)
后台日志：
```
ymy139@raspberrypi:~/Servers/koishi $ sudo yarn start
yarn run v1.22.19
$ koishi start
2023-08-21 13:26:45 [I] app Koishi/4.14.1
2023-08-21 13:26:45 [I] app apply plugin group:entry
2023-08-21 13:26:45 [I] app apply plugin group:basic
2023-08-21 13:26:45 [I] app apply plugin commands
2023-08-21 13:26:45 [I] app apply plugin help
2023-08-21 13:26:45 [I] app apply plugin locales
2023-08-21 13:26:45 [I] app apply plugin rate-limit
2023-08-21 13:26:45 [I] app apply plugin group:console
2023-08-21 13:26:45 [I] app apply plugin analytics
2023-08-21 13:26:45 [I] app apply plugin config
2023-08-21 13:26:45 [I] app apply plugin console
2023-08-21 13:26:45 [I] app apply plugin dataview
2023-08-21 13:26:45 [I] app apply plugin explorer
2023-08-21 13:26:45 [I] app apply plugin logger
2023-08-21 13:26:45 [I] app apply plugin insight
2023-08-21 13:26:45 [I] app apply plugin market
2023-08-21 13:26:46 [I] app apply plugin sandbox
2023-08-21 13:26:46 [I] app apply plugin status
2023-08-21 13:26:46 [I] app apply plugin theme-vanilla
2023-08-21 13:26:46 [I] app apply plugin group:storage
2023-08-21 13:26:46 [I] app apply plugin database-sqlite
2023-08-21 13:26:46 [I] app apply plugin assets-local
2023-08-21 13:26:46 [I] app apply plugin group:adapter
2023-08-21 13:26:46 [I] app apply plugin gocqhttp
2023-08-21 13:26:46 [I] assets missing config "selfUrl", fallback to "file:" scheme
2023-08-21 13:26:46 [I] app server listening at http://127.0.0.1:5140
2023-08-21 13:26:47 [I] sqlite auto creating table user
2023-08-21 13:26:47 [I] sqlite auto creating table binding
2023-08-21 13:26:47 [I] sqlite auto creating table channel
2023-08-21 13:26:47 [I] sqlite auto creating table stats_daily
2023-08-21 13:26:47 [I] sqlite auto creating table stats_hourly
2023-08-21 13:26:47 [I] sqlite auto creating table stats_longterm
2023-08-21 13:26:51 [W] market timeout of 5000ms exceeded
2023-08-21 13:26:51 [W] market timeout of 5000ms exceeded
2023-08-21 13:26:51 [W] market timeout of 5000ms exceeded
2023-08-21 13:26:51 [W] market timeout of 5000ms exceeded
2023-08-21 13:26:51 [W] market timeout of 5000ms exceeded
2023-08-21 13:26:51 [W] market timeout of 5000ms exceeded
2023-08-21 13:26:51 [W] market timeout of 5000ms exceeded
2023-08-21 13:26:51 [W] market timeout of 5000ms exceeded
2023-08-21 13:26:51 [W] market timeout of 5000ms exceeded
2023-08-21 13:26:51 [W] market timeout of 5000ms exceeded
2023-08-21 13:26:52 [W] market Error: read ECONNRESET
                            at AxiosError.from (/home/ymy139/apps/koishi/app/node_modules/axios/dist/node/axios.cjs:836:14)
                            at RedirectableRequest.handleRequestError (/home/ymy139/apps/koishi/app/node_modules/axios/dist/node/axios.cjs:3010:25)
                            at RedirectableRequest.emit (node:events:526:35)
                            at eventHandlers.<computed> (/home/ymy139/apps/koishi/app/node_modules/follow-redirects/index.js:14:24)
                            at ClientRequest.emit (node:events:514:28)
                            at TLSSocket.socketErrorListener (node:_http_client:501:9)
                            at TLSSocket.emit (node:events:514:28)
                            at emitErrorNT (node:internal/streams/destroy:151:8)
                            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-08-21 13:26:52 [W] market Error: read ECONNRESET
                            at AxiosError.from (/home/ymy139/apps/koishi/app/node_modules/axios/dist/node/axios.cjs:836:14)
                            at RedirectableRequest.handleRequestError (/home/ymy139/apps/koishi/app/node_modules/axios/dist/node/axios.cjs:3010:25)
                            at RedirectableRequest.emit (node:events:526:35)
                            at eventHandlers.<computed> (/home/ymy139/apps/koishi/app/node_modules/follow-redirects/index.js:14:24)
                            at ClientRequest.emit (node:events:514:28)
                            at TLSSocket.socketErrorListener (node:_http_client:501:9)
                            at TLSSocket.emit (node:events:514:28)
                            at emitErrorNT (node:internal/streams/destroy:151:8)
                            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

---

### Versions

- OS: Raspberry Pi OS with desktop (32bit, v6.1, arm v8a)
- Platform: /
- Node version: 18.17.0
- Koishi version: 4.14.1

---

**Comment by ymy139** [comment]
已修改issue
以下为market插件配置项：
```
registry.endpoint = https://registry.npmmirror.com
registry.timeout = 5000
search.endpoint = https://registry.koishi.chat/index.json
search.timeout = 30000
search.proxyAgent = *None*
```

**Comment by shigma** [comment]
那看起来你更换的源指的是 registry.endpoint 而非 search.endpoint。图中的报错与后者相关。

请更换更好的网络环境，或者在论坛中搜索第三方的插件市场镜像。

**Comment by ymy139** [comment]
在更换 search.endpoint 为 https://registry.koishi.t4wefan.pub/index.json 后即可正常使用插件市场。
