### ISSUE TITLE
Bug: admin插件的2.0.0-alpha.0版本无法提供相关的指令

### ISSUE THREAD

**Issue by esirprus** [koishijs/koishi#1182]
### Describe the bug

我安装了admin插件的2.0.0-alpha.0版本后发现插件配置中并没有提供诸如auth的指令，而是一片空白。

### Steps to reproduce

安装admin插件的2.0.0-alpha.0版本，及其相关依赖。启用相关插件。

### Expected behavior

启用相关插件后，admin插件配置能够正常显示提供的命令

### Screenshots

插件配置页面
![image](https://github.com/koishijs/koishi/assets/44423036/c608dde1-108a-4bcc-8e65-ad4daed4fc39)

Koishi日志：
![image](https://github.com/koishijs/koishi/assets/44423036/112e29b6-2a96-469b-9d14-0ab42abd4a32)

 TypeError: query expr under $el is not supported
                            at Object.$el (C:\Users\esirp\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql-utils\lib\index.js:75:17)
                            at SQLiteBuilder.parseFieldQuery (C:\Users\esirp\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql-utils\lib\index.js:171:52)
                            at SQLiteBuilder.parseQuery (C:\Users\esirp\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql-utils\lib\index.js:189:30)
                            at SQLiteBuilder.get (C:\Users\esirp\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql-utils\lib\index.js:257:25)
                            at SQLiteDriver.eval (C:\Users\esirp\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js:292:27)
                            at Executable.execute (C:\Users\esirp\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\core\lib\index.cjs:385:34)
                            at async _Admin.start (C:\Users\esirp\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\plugin-admin\lib\index.js:271:20)
                            at async C:\Users\esirp\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:739:7
                            at async Promise.all (index 1)
                            at async _Lifecycle.flush (C:\Users\esirp\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:82:7)

### Versions

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

Binaries:
    Node: 16.19.1
    Yarn: 3.5.0

Koishi:
    Core: 4.14.2
    Console: 5.13.2
    Koishi Desktop: 0.10.6

**Comment by Hieuzest** [comment]
[这里](https://github.com/koishijs/webui/blob/6b586e3f669071426013fcb6f2b273d066d157f7/plugins/admin/src/index.ts#L54-L55) 存在一个在创建用户组时name为null的bug，导致了此问题

只需先给用户组改名后再添加用户即可回避此问题
