### ISSUE TITLE
Bug: koishi v4.14.5 cannot reply messages to me in the sandbox

### ISSUE THREAD

**Issue by initialencounter** [koishijs/koishi#1196]
### Describe the bug

koishi v4.14.5 沙盒无法回复消息

### Steps to reproduce

将 `koishi` 更新到 `4.14.5` 版本，在沙盒发送 `echo 123` 或者 `help`

### Expected behavior

回复消息

### Screenshots

![image](https://github.com/koishijs/koishi/assets/109729945/ae744464-f060-43e1-ad08-7e4db3627011)
![image](https://github.com/koishijs/koishi/assets/109729945/d42d97b5-1eed-4e99-9b32-30d56dba8826)

```
2023-09-10 18:36:18 [W] session echo 123
                        TypeError: Cannot read properties of undefined (reading 'slice')
                            at get stripped [as stripped] (D:\dev\koimux_bot\node_modules\@koishijs\core\lib\index.cjs:2066:36)
                            at get parsed [as parsed] (D:\dev\koimux_bot\node_modules\@koishijs\core\lib\index.cjs:2057:17)
                            at _Session.<anonymous> (D:\dev\koimux_bot\node_modules\@koishijs\core\lib\index.cjs:1831:29) 
                            at _Lifecycle.emit (D:\dev\koimux_bot\node_modules\cordis\lib\index.cjs:105:16)
                            at _Context.emit (D:\dev\koimux_bot\node_modules\cordis\lib\index.cjs:650:31)
                            at _Processor._process (D:\dev\koimux_bot\node_modules\@koishijs\core\lib\index.cjs:798:14)   
                            at next (D:\dev\koimux_bot\node_modules\@koishijs\core\lib\index.cjs:844:69)
                            at _Processor._handleMessage (D:\dev\koimux_bot\node_modules\@koishijs\core\lib\index.cjs:855:28)
                            at _Lifecycle.emit (D:\dev\koimux_bot\node_modules\cordis\lib\index.cjs:105:16)
                            at _Context.emit (D:\dev\koimux_bot\node_modules\cordis\lib\index.cjs:650:31)
```
![image](https://github.com/koishijs/koishi/assets/109729945/53dd5085-6f0b-463d-9584-82ba1e432c70)

### Versions

- OS: Windows 11 
- Platform: Sandbox
- Node version: 18.16.0
- Koishi version: 4.14.5

### Additional context

koishi v4.14.5， sandbox v3.1.12 和 v3.1.11 都会触发该bug;
koishi v4.14.4不会触发该bug

**Comment by shigma** [comment]
沙盒以外的环境正常吗？

**Comment by initialencounter** [comment]
谢谢你!  Thank you!

**Comment by shigma** [comment]
已修复。

**Comment by initialencounter** [comment]
> 

onebot是正常的，其他平台没试过
