### ISSUE TITLE
Bug:  telegram適配器錯誤  app TypeError: Cannot read properties of undefined (reading 'dispatch')

### ISSUE THREAD

**Issue by qilincai** [koishijs/koishi#1216]
### Describe the bug

telegram適配器錯誤
`2023-10-06 14:30:00 [W] app TypeError: Cannot read properties of undefined (reading 'dispatch')
                            at handleUpdate (/Users/buildmaster/bot/test/koishi-app/node_modules/@satorijs/adapter-telegram/lib/index.js:236:14)
                            at polling (/Users/buildmaster/bot/test/koishi-app/node_modules/@satorijs/adapter-telegram/lib/index.js:589:13)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

### Steps to reproduce

透過npm init koishi創建一個新的koishi project
(版本4.15.0)
npm install後npm run start
選擇telegram適配器
輸入bot token並選擇polling mode
然後就跳出上述錯誤

### Expected behavior

正常運行

### Versions

- OS: mac os
- Platform: telegram
- Node version: 18.14.2
- Koishi version: 4.15.0

**Comment by XxLittleCxX** [comment]
https://github.com/satorijs/satori/commit/6027e236a095da8d45f10a35285feb7a51796fe3

**Comment by shigma** [comment]
已修复，感谢反馈。
