### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by shumyun** [koishijs/koishi#1218]
### Describe the bug

2023-10-11 21:49:35 [W] mysql INSERT INTO `binding` (`aid`, `bid`, `pid`, `platform`) VALUES (1, 1, NULL, 'kook')
2023-10-11 21:49:35 [W] session 帮助
                        ER_BAD_NULL_ERROR: Column 'pid' cannot be null
                            at _MySQLDriver.query (D:\personal\youkey-app\node_modules\@minatojs\driver-mysql\src\index.ts:361:19)
                            at _MySQLDriver.create (D:\personal\youkey-app\node_modules\@minatojs\driver-mysql\src\index.ts:476:31)
                            at _Executable.execute (D:\personal\youkey-app\node_modules\@minatojs\core\src\selection.ts:98:40)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at _DatabaseService.createUser (D:\personal\youkey-app\node_modules\@koishijs\core\src\database.ts:144:5)
                            at _Session.observeUser (D:\personal\youkey-app\node_modules\@koishijs\core\src\session.ts:312:18)
                            at _Processor.attach (D:\personal\youkey-app\node_modules\@koishijs\core\src\middleware.ts:230:20)
                            at next (D:\personal\youkey-app\node_modules\@koishijs\core\src\middleware.ts:267:16)
                            at _Processor._handleMessage (D:\personal\youkey-app\node_modules\@koishijs\core\src\middleware.ts:278:22)

### Steps to reproduce

rt

### Expected behavior

rt

### Versions

- @koishijs/plugin-adapter-kook: 4.0.3
- @koishijs/plugin-database-mysql: 5.5.1 
- Koishi version: 4.15.0

**Comment by MaikoTan** [comment]
Please fill up the title as well as the content, otherwise we cannot determine what is going wrong.

请填写标题和内容，否则我们无法确定问题所在。

**Comment by shigma** [comment]
请尝试将 kook 适配器更新至 4.0.4 版本，看是否解决了你的问题。

**Comment by shumyun** [comment]
已经解决！
