### ISSUE TITLE
Bug: kook平台无法发送图片

### ISSUE THREAD

**Issue by TTsdzb** [koishijs/koishi#1239]
### Describe the bug

当发送的消息中包含图片时，图片并不会发出，后台报错。对于单张图片，Bot 不会发送任何消息；对于混合消息段，Bot 只会发送文本。无论 `handleMixedContent` 为 `separate` 还是 `card` 均无法发送。

#### 链接图片

1. 安装 `tex` 插件
2. 在 kook 触发 `tex` 指令

#### Puppeteer 生成图片

1. 安装 `color` 插件
2. 在 kook 触发 `color` 指令

### Expected behavior

Bot 发送生成的图片。

### Versions

- OS: Debian 11
- Platform: kook
- Node version: 18.17.1
- Koishi version: 4.15.2
- @koishijs/plugin-adapter-kook version: 4.0.6

#### 后台日志

```
2023-10-24 19:07:20 [W] session TypeError: Cannot read properties of undefined (reading 'id')                                                     
                            at /home/pi/koishi/node_modules/.pnpm/@satorijs+core@3.0.1/node_modules/@satorijs/core/lib/index.cjs:341:46
                            at Array.map (<anonymous>)
                            at _KookBot.sendMessage (/home/pi/koishi/node_modules/.pnpm/@satorijs+core@3.0.1/node_modules/@satorijs/core/lib/index.cjs:341:21)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async /home/pi/koishi/node_modules/.pnpm/@koishijs+core@4.15.2/node_modules/@koishijs/core/lib/index.cjs:2194:7
                            at async _Session.withScope (/home/pi/koishi/node_modules/.pnpm/@koishijs+core@4.15.2/node_modules/@koishijs/core/lib/index.cjs:2090:22)
                            at async next (/home/pi/koishi/node_modules/.pnpm/@koishijs+core@4.15.2/node_modules/@koishijs/core/lib/index.cjs:1055:16)
                            at async next (/home/pi/koishi/node_modules/.pnpm/@koishijs+core@4.15.2/node_modules/@koishijs/core/lib/index.cjs:1055:16)
                            at async next (/home/pi/koishi/node_modules/.pnpm/@koishijs+core@4.15.2/node_modules/@koishijs/core/lib/index.cjs:1055:16)
                            at async _Processor._handleMessage (/home/pi/koishi/node_modules/.pnpm/@koishijs+core@4.15.2/node_modules/@koishijs/core/lib/index.cjs:1066:22)
```

**Comment by maxoyed** [comment]
贴一下代码看看，我这边KOOK可以正常发送图片的
![image](https://github.com/koishijs/koishi/assets/25519245/69d6b811-ef8a-4373-9955-9466d4c3061e)

**Comment by TTsdzb** [comment]
所有图片都不能发送。不仅仅是我自己写的插件，官方插件一样不能发送图片。

具体你可以参考官方的 `color` 插件。实际症状就是，指令发出来后，bot 完全不会发送任何内容。

**Comment by ilharp** [comment]
有两个可能的原因：

1. 这两个插件都要求你的电脑上有安装 Chrome 系浏览器并能够启动。你可能没有安装浏览器。
1. Koishi 目前不支持 pnpm，因此在 pnpm 上 Koishi 可能会正常工作，也可能不会。

**Comment by maxoyed** [comment]
> 所有图片都不能发送。不仅仅是我自己写的插件，官方插件一样不能发送图片。
> 
> 具体你可以参考官方的 `color` 插件。实际症状就是，指令发出来后，bot 完全不会发送任何内容。
> 

我直接发b64的图片能发出去

**Comment by TTsdzb** [comment]
> 我直接发b64的图片能发出去

这并不能解决问题。我总不能把官方插件发送图片的方式都改成 b64 吧...

**Comment by ilharp** [comment]
> 我总不能把官方插件或者其他人写的插件发送图片的方式都改成 b64 吧...

直接发送 base64 图片成功证明了在 Kook 平台发送图片没有问题。你遇到的是其他问题。

此 Issue 可以被关闭。Koishi 使用方面的问题可以前往 Discussions 版或 Koishi 论坛继续提问。
