### ISSUE TITLE
Bug: 当全局设置 autoAuthorize 为 0 时 一个不在数据库的用户执行命令 会报错

### ISSUE THREAD

**Issue by 502647092** [koishijs/koishi#1267]
### Describe the bug

当全局设置 autoAuthorize 为 0 时 一个不在数据库的用户执行命令 会报错

### Steps to reproduce

设置 autoAuthorize 为 0
找一个数据库不存在的用户
执行任意命令

### Expected behavior

正常运行

### Screenshots

错误日志
```
2023-11-16 12:08:29 [W] app Error: user not found                                                                                                                                                                 
                            at Proxy.setUser (/home/project/TSWorkSpace/koishi/development/koishi-app/node_modules/@koishijs/core/src/database.ts:136:25)                                                         
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                         
                            at _Processor._handleMessage (/home/project/TSWorkSpace/koishi/development/koishi-app/node_modules/@koishijs/core/src/middleware.ts:279:7)                                            
```

### Versions

System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-2696 v2 @ 2.50GHz

Binaries:
    Node: 20.9.0
    Yarn: 1.22.19

Koishi:
    Core: 4.15.5
    Console: 5.18.5

**Comment by maxoyed** [comment]
最低权限是1，我之前也手动设置0，其实用1就没事了

**Comment by Hieuzest** [comment]
https://github.com/koishijs/koishi/blob/8a2d13db98c2b34a0d5f3f129183e5399423504d/packages/core/src/session.ts#L273

Shoule be like
```
cache = observe(data, diff => (data as any).$detached || this.app.database.setUser(this.platform, userId, diff as any), `user ${this.uid}`)
```
