### ISSUE TITLE
Bug: status和过滤器

### ISSUE THREAD

**Issue by imAkisa** [koishijs/koishi#1277]
### Describe the bug

```
2023-11-21 20:24:47 [W] app TypeError: Cannot read properties of undefined (reading 'get')
                            at Proxy.get (/home/akisa/bots/koishi_mail/node_modules/@koishijs/plugin-status/lib/index.js:216:39)
                            at async Proxy.refresh (/home/akisa/bots/koishi_mail/node_modules/@koishijs/console/lib/index.js:56:14)
```
只要我给 status 插件设置了过滤器（目前只试过用户和平台），然后重启 koishi 就会报上面的warn，且控制台的右下角显示异常

### Steps to reproduce

给 status 插件设置过滤器，然后重启 koishi

### Expected behavior

就，正常使用

### Screenshots

<img width="1250" alt="Midgard_11-21_20-29-52" src="https://github.com/koishijs/koishi/assets/108515435/dd99b8ce-2c80-48a6-bea6-7608cdfbeb3d">
<img width="1250" alt="Midgard_11-21_20-30-38" src="https://github.com/koishijs/koishi/assets/108515435/51026b42-19e9-401a-a955-ab3749aaabf2">

### Versions

System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
Binaries:
    Node: 18.18.0
    Yarn: 4.0.1
Koishi:
    Core: 4.15.6
    Console: 5.19.1
    @koishijs/plugin-status: 7.2.5

**Comment by imAkisa** [comment]
![image](https://github.com/koishijs/koishi/assets/108515435/a186b169-c06a-40e7-a058-066423a86f77)
