### ISSUE TITLE
Bug: 改变插件分组后调用 help 指令导致的爆栈

### ISSUE THREAD

**Issue by SaarChaffee** [koishijs/koishi#1286]
### Describe the bug

```log

2023-11-26 20:00:06 [W] app RangeError: Maximum call stack size exceeded
                            at fork.parent.filter (/koishi/node_modules/@koishijs/loader/lib/shared.js:264:26)
                            at fork.parent.filter (/koishi/node_modules/@koishijs/loader/lib/shared.js:265:21)
                            at fork.parent.filter (/koishi/node_modules/@koishijs/loader/lib/shared.js:265:21)
                            at fork.parent.filter (/koishi/node_modules/@koishijs/loader/lib/shared.js:265:21)
                            at fork.parent.filter (/koishi/node_modules/@koishijs/loader/lib/shared.js:265:21)
                            at fork.parent.filter (/koishi/node_modules/@koishijs/loader/lib/shared.js:265:21)
                            at fork.parent.filter (/koishi/node_modules/@koishijs/loader/lib/shared.js:265:21)
                            at fork.parent.filter (/koishi/node_modules/@koishijs/loader/lib/shared.js:265:21)
                            at fork.parent.filter (/koishi/node_modules/@koishijs/loader/lib/shared.js:265:21)
                            at fork.parent.filter (/koishi/node_modules/@koishijs/loader/lib/shared.js:265:21)
```

在 bot 上表现为 koishi 不理人（假死了）

### Steps to reproduce

1. 找一个有指令的插件，有提示（提供了以下指令：xxxx）。
![0b3a3d7d851ab7f9bd256a6f14355beb](https://github.com/koishijs/koishi/assets/53519746/10559e2e-765e-4beb-bde1-a541a16afe41)

2.将这个插件移动到不同分组，确保提示（提供了以下指令：xxxx）消失，并点重载配置。
![d0bba5e0f6a8e184252ffa12dad0e53e](https://github.com/koishijs/koishi/assets/53519746/578aeb1b-b17c-4c65-aa16-da15625a9815)

3.调用help触发Maximum call stack size exceeded！

### Expected behavior

能正确相应指令。

### Versions

System:
    OS: Linux 5.4 Alpine Linux
    CPU: (1) x64 Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz

Binaries:
    Node: 20.9.0
    Yarn: 1.22.19

Koishi:
    Core: 4.15.6
    Console: 5.19.4

**Comment by shigma** [comment]
然后重启程序可以解决是吗？

**Comment by SaarChaffee** [comment]
是的，重启 koishi 或者直接在全局配置那个地方重载配置可以解决。
