### ISSUE TITLE
Bug: Telegram 群聊内点击按钮报错

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1315]
### Describe the bug

按钮数据如下

```
reply_markup: {
                            inline_keyboard: [
                                [
                                    {
                                        text: "test-button",
                                        callback_data: "test-button",
                                    }
                                ]
                            ]
                        }
```

点击按钮后，koishi接收到事件报错

```
 app TypeError: Cannot read properties of undefined (reading 'chat')
                            at handleUpdate (E:\Project\koishi-app\node_modules\@satorijs\adapter-telegram\src\utils.ts:83:14)
                            at Timeout.polling (E:\Project\koishi-app\node_modules\@satorijs\adapter-telegram\src\polling.ts:44:13)        
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps to reproduce

如题

### Expected behavior

如题

### Versions

    "@koishijs/client": "^5.22.0",
    "@koishijs/plugin-hmr": "^1.2.6",
    "@koishijs/scripts": "^4.5.0",
    "@types/node": "^20.10.2",
    "cross-env": "^7.0.3",
    "esbuild": "^0.18.20",
    "esbuild-register": "npm:@shigma/esbuild-register@^1.1.1",
    "typescript": "^5.3.2",
    "yakumo": "^1.0.0-alpha.4",
    "yakumo-esbuild": "^1.0.0-alpha.0",
    "yakumo-esbuild-yaml": "^1.0.0-alpha.0",
    "yakumo-publish-sync": "^1.0.0-alpha.1",
    "yakumo-tsc": "^1.0.0-alpha.1",
    "yml-register": "^1.1.0"
    "@koishijs/plugin-actions": "^0.0.2",
    "@koishijs/plugin-adapter-discord": "^4.1.7",
    "@koishijs/plugin-adapter-kook": "^4.3.0",
    "@koishijs/plugin-adapter-qq": "^4.2.1",
    "@koishijs/plugin-adapter-satori": "^1.0.3",
    "@koishijs/plugin-adapter-telegram": "^4.2.0",
    "@koishijs/plugin-admin": "^2.0.0-alpha.5",
    "@koishijs/plugin-analytics": "^2.0.3",
    "@koishijs/plugin-auth": "^4.1.6",
    "@koishijs/plugin-bind": "^1.4.5",
    "@koishijs/plugin-commands": "^3.4.3",
    "@koishijs/plugin-config": "^2.7.0",
    "@koishijs/plugin-console": "^5.22.0",
    "@koishijs/plugin-database-sqlite": "^3.8.3",
    "@koishijs/plugin-explorer": "^1.5.0",
    "@koishijs/plugin-help": "^2.4.1",
    "@koishijs/plugin-insight": "^3.4.4",
    "@koishijs/plugin-inspect": "^1.1.3",
    "@koishijs/plugin-locales": "^2.5.1",
    "@koishijs/plugin-logger": "^2.6.1",
    "@koishijs/plugin-market": "^2.7.1",
    "@koishijs/plugin-oobe": "^0.0.2",
    "@koishijs/plugin-sandbox": "^3.2.2",
    "@koishijs/plugin-server": "^3.1.3",
    "@koishijs/plugin-server-satori": "^2.4.0",
    "@koishijs/plugin-server-temp": "^1.2.0",
    "@koishijs/plugin-status": "^7.3.0",
    "koishi": "^4.16.1",
    "koishi-plugin-android": "^0.0.1",
    "koishi-plugin-assets-local": "^3.2.0",
    "koishi-plugin-dataview": "^2.6.1",
    "koishi-plugin-desktop": "^0.0.4",
    "koishi-plugin-puppeteer": "^3.7.3",
    "koishi-plugin-rate-limit": "^2.0.1",
    "koishi-plugin-telemetry": "^0.0.2",
    "koishi-plugin-theme-vanilla": "^1.0.6"

**Comment by XxLittleCxX** [comment]
没有复现出来，怎么发送的消息，能否提供更完整的代码

**Comment by XxLittleCxX** [comment]
有没有用 inline mode

**Comment by Ice-Hazymoon** [comment]
> 有没有用 inline mode

没明白这句话是什么意思
