### ISSUE TITLE
Bug: Sqlite 使用 `regexFor` 报错

### ISSUE THREAD

**Issue by TTsdzb** [koishijs/koishi#1324]
### Describe the bug

当使用 [regexFor](https://koishi.chat/zh-CN/api/database/query.html#regexfor) 进行查询时数据库报错：

```
2024-01-04 21:22:46 [W] sqlite > SELECT `id`, `title`, `type`, `artist`, `genre`, `bpm`, `release_date`, `from`, `is_new` FROM `maimaidx.music_info` urekuxcz WHERE '.*PANDORA PARADOXXX.*' regexp `title` []
2024-01-04 21:22:46 [W] command mai.search.title PANDORA PARADOXXX
                        Error
                            at f.handleError (/home/l/workspace/koishi/node_modules/.pnpm/@minatojs+sql.js@3.1.0/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at c.step (/home/l/workspace/koishi/node_modules/.pnpm/@minatojs+sql.js@3.1.0/node_modules/@minatojs/sql.js/dist/sql-wasm.js:80:205)
                            at <anonymous> (/home/l/workspace/koishi/node_modules/.pnpm/@minatojs+driver-sqlite@3.8.4_@minatojs+core@2.8.1/node_modules/@minatojs/driver-sqlite/src/index.ts:316:19)
                            at _SQLiteDriver.#exec (/home/l/workspace/koishi/node_modules/.pnpm/@minatojs+driver-sqlite@3.8.4_@minatojs+core@2.8.1/node_modules/@minatojs/driver-sqlite/src/index.ts:302:22)
                            at _SQLiteDriver.#all (/home/l/workspace/koishi/node_modules/.pnpm/@minatojs+driver-sqlite@3.8.4_@minatojs+core@2.8.1/node_modules/@minatojs/driver-sqlite/src/index.ts:313:12)
                            at _SQLiteDriver.get (/home/l/workspace/koishi/node_modules/.pnpm/@minatojs+driver-sqlite@3.8.4_@minatojs+core@2.8.1/node_modules/@minatojs/driver-sqlite/src/index.ts:370:18)
                            at _Selection.execute (/home/l/workspace/koishi/node_modules/.pnpm/@minatojs+core@2.8.1/node_modules/@minatojs/core/src/selection.ts:100:40)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at _Command.<anonymous> (/home/l/workspace/koishi/external/maimaidx/src/commands/search.tsx:46:22)
                            at Array.<anonymous> (/home/l/workspace/koishi/node_modules/.pnpm/@koishijs+core@4.16.3/node_modules/@koishijs/core/src/command/command.ts:299:14)
```

### Steps to reproduce

数据表扩展：

```ts
/**
 * Extend table `maimaidx.music_info` on the given context.
 * @param ctx The context of koishi
 */
export function extendMusicInfo(ctx: Context) {
  ctx.model.extend(
    "maimaidx.music_info",
    {
      id: "unsigned",
      title: "string",
      type: "string",
      artist: "string",
      genre: "string",
      bpm: "unsigned",
      release_date: "string",
      from: "string",
      is_new: "boolean",
    },
    {
      primary: "id",
      autoInc: false,
    }
  );
}
```

查询数据：

```ts
// Query the database for music.
const musics = await ctx.database.get("maimaidx.music_info", {
  title: { $regexFor: `.*${title}.*` },
});
```

### Expected behavior

能正确查询数据库并返回结果。

### Screenshots

聊天记录截图：

![图片](https://github.com/koishijs/koishi/assets/62687036/96be8fab-abad-4f57-b14f-009b20da5e44)

### Versions

- OS: Arch Linux
- Platform: sandbox
- Node version: 21.5.0
- Koishi version: 4.16.3
- @koishijs/plugin-database-sqlite: 3.8.4

### Additional context

疑似生成的 SQL 语句中列名和正则表达式的位置反了，我手动修改并运行生成的语句可以查询出结果：

![图片](https://github.com/koishijs/koishi/assets/62687036/a80a3ef4-2ce7-4c32-b585-22ed6988cf66)

SQLite version: 3.44.2

**Comment by shigma** [comment]
感觉是你写反了，应该使用 $regex 而不是 $regexFor

**Comment by TTsdzb** [comment]
> 感觉是你写反了，应该使用 $regex 而不是 $regexFor

解决了，我的问题。感谢
