### ISSUE TITLE
Bug: What happen

### ISSUE THREAD

**Issue by onepunya** [koishijs/koishi#1397]
### Describe the bug

/home/container/node_modules/@koishijs/loader/lib/index.js:50
  static {
         ^

SyntaxError: Unexpected token '{'
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/container/node_modules/koishi/lib/index.cjs:36:29)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

### Steps to reproduce

P

### Expected behavior

Help

### Screenshots

P

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version: 

### Additional context

Is there any problem?

**Comment by shigma** [comment]
Please upgrade your node.js version.

https://nodejs.org/en
