### ISSUE TITLE
Bug: 安装/升级插件超时

### ISSUE THREAD

**Issue by wuyukwi** [koishijs/koishi#1422]
### Describe the bug

安装/升级插件超时

### Steps to reproduce

树莓派Raspberry Pi OS上Docker安装然后打开控制台安装插件

### Expected behavior

正常安装插件

### Screenshots

2024-07-07 04:26:02 [I] app Koishi/4.17.7
2024-07-07 04:26:02 [I] loader apply plugin group:entry
2024-07-07 04:26:02 [I] loader apply plugin group:server
2024-07-07 04:26:02 [I] loader apply plugin server:emdlaa
2024-07-07 04:26:02 [I] loader apply plugin group:basic
2024-07-07 04:26:02 [I] loader apply plugin commands:dzapym
2024-07-07 04:26:02 [I] loader apply plugin help:6agjt2
2024-07-07 04:26:02 [I] loader apply plugin http:46ym4m
2024-07-07 04:26:02 [I] loader apply plugin locales:eagx0j
2024-07-07 04:26:02 [I] loader apply plugin proxy-agent:dy41up
2024-07-07 04:26:03 [I] loader apply plugin rate-limit:rovpx5
2024-07-07 04:26:03 [I] loader apply plugin telemetry:42h721
2024-07-07 04:26:03 [I] loader apply plugin group:console
2024-07-07 04:26:03 [I] loader apply plugin actions:ccycii
2024-07-07 04:26:03 [I] loader apply plugin analytics:8b97pv
2024-07-07 04:26:03 [I] loader apply plugin config:ovud3h
2024-07-07 04:26:03 [I] loader apply plugin console:3a9nsk
2024-07-07 04:26:03 [I] loader apply plugin dataview:6ztq0n
2024-07-07 04:26:03 [I] loader apply plugin explorer:s7iwdz
2024-07-07 04:26:03 [I] loader apply plugin logger:is7cwi
2024-07-07 04:26:03 [I] loader apply plugin insight:ar6yz1
2024-07-07 04:26:03 [I] loader apply plugin market:hmu4p7
2024-07-07 04:26:03 [I] loader apply plugin notifier:76wl1t
2024-07-07 04:26:03 [I] loader apply plugin oobe:i94n3t
2024-07-07 04:26:03 [I] loader apply plugin sandbox:574tnm
2024-07-07 04:26:03 [I] loader apply plugin status:sapjym
2024-07-07 04:26:03 [I] loader apply plugin theme-vanilla:pygmlg
2024-07-07 04:26:03 [I] loader apply plugin group:storage
2024-07-07 04:26:03 [I] loader apply plugin database-sqlite:9h36ud
2024-07-07 04:26:03 [I] loader apply plugin assets-local:na1wxx
2024-07-07 04:26:03 [I] loader apply plugin group:adapter
2024-07-07 04:26:03 [I] assets missing config "selfUrl", fallback to "file:" scheme
2024-07-07 04:26:04 [I] server server listening at http://0.0.0.0:5140
2024-07-07 04:26:04 [I] console webui is available at http://127.0.0.1:5140
2024-07-07 04:28:19 [I] market Yarn 4.1.1
2024-07-07 04:28:19 [I] market ┌ Resolution step
2024-07-07 04:28:22 [I] market + @koishijs/plugin-adapter-qq@npm:4.7.5, @koishijs/plugin-echo@npm:2.2.5, koishi-plugin-adapter-onebot@npm:6.5.8, koishi@npm:4.17.9, and 17 more.
2024-07-07 04:28:22 [I] market - @cordisjs/core@npm:3.16.0, @cordisjs/loader@npm:0.11.0, @cordisjs/logger@npm:0.3.2, @koishijs/core@npm:4.17.7, @koishijs/loader@npm:4.5.7, and 7 more.
2024-07-07 04:28:22 [I] market └ Completed in 2s 412ms
2024-07-07 04:28:22 [I] market ┌ Post-resolution validation
2024-07-07 04:28:22 [I] market └ Completed
2024-07-07 04:28:22 [I] market ┌ Fetch step
2024-07-07 04:30:59 [I] market Yarn 4.1.1
2024-07-07 04:30:59 [I] market ┌ Resolution step
2024-07-07 04:31:00 [I] market + @koishijs/plugin-adapter-qq@npm:4.7.5, koishi-plugin-adapter-onebot@npm:6.5.8, koishi@npm:4.17.9, @cordisjs/core@npm:3.17.4, @cordisjs/loader@npm:0.12.4, and 15 more.
2024-07-07 04:31:00 [I] market - @cordisjs/core@npm:3.16.0, @cordisjs/loader@npm:0.11.0, @cordisjs/logger@npm:0.3.2, @koishijs/core@npm:4.17.7, @koishijs/loader@npm:4.5.7, and 7 more.
2024-07-07 04:31:00 [I] market └ Completed in 1s 98ms
2024-07-07 04:31:00 [I] market ┌ Post-resolution validation
2024-07-07 04:31:00 [I] market └ Completed
2024-07-07 04:31:00 [I] market ┌ Fetch step
2024-07-07 04:32:30 [W] market RequestError: Timeout awaiting 'socket' for 60000ms
                            at ClientRequest.<anonymous> (/koishi/.yarn/releases/yarn-4.1.1.cjs:147:14230)
                            at Object.onceWrapper (node:events:634:26)
                            at ClientRequest.emit (node:events:531:35)
                            at u.emit (/koishi/.yarn/releases/yarn-4.1.1.cjs:142:14420)
                            at TLSSocket.socketErrorListener (node:_http_client:500:9)
                            at TLSSocket.emit (node:events:519:28)
                            at emitErrorNT (node:internal/streams/destroy:169:8)
                            at emitErrorCloseNT (node:internal/streams/destroy:128:3)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
                            at h (/koishi/.yarn/releases/yarn-4.1.1.cjs:143:15132)
                            at ClientRequest.I (/koishi/.yarn/releases/yarn-4.1.1.cjs:143:15376)
                            at Object.onceWrapper (node:events:633:28)
                            at ClientRequest.emit (node:events:531:35)
                            at u.emit (/koishi/.yarn/releases/yarn-4.1.1.cjs:142:14420)
                            at TLSSocket.emitRequestTimeout (node:_http_client:845:9)
                            at Object.onceWrapper (node:events:633:28)
                            at TLSSocket.emit (node:events:531:35)
                            at Socket._onTimeout (node:net:590:8)
                            at listOnTimeout (node:internal/timers:573:17)
2024-07-07 04:32:30 [I] market └ Completed in 4m 8s
2024-07-07 04:32:30 [W] market Failed with errors in 4m 11s
2024-07-07 04:35:08 [W] market RequestError: Timeout awaiting 'socket' for 60000ms
                            at ClientRequest.<anonymous> (/koishi/.yarn/releases/yarn-4.1.1.cjs:147:14230)
                            at Object.onceWrapper (node:events:634:26)
                            at ClientRequest.emit (node:events:531:35)
                            at u.emit (/koishi/.yarn/releases/yarn-4.1.1.cjs:142:14420)
                            at TLSSocket.socketErrorListener (node:_http_client:500:9)
                            at TLSSocket.emit (node:events:519:28)
                            at emitErrorNT (node:internal/streams/destroy:169:8)
                            at emitErrorCloseNT (node:internal/streams/destroy:128:3)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
                            at h (/koishi/.yarn/releases/yarn-4.1.1.cjs:143:15132)
                            at ClientRequest.I (/koishi/.yarn/releases/yarn-4.1.1.cjs:143:15376)
                            at Object.onceWrapper (node:events:633:28)
                            at ClientRequest.emit (node:events:531:35)
                            at u.emit (/koishi/.yarn/releases/yarn-4.1.1.cjs:142:14420)
                            at TLSSocket.emitRequestTimeout (node:_http_client:845:9)
                            at Object.onceWrapper (node:events:633:28)
                            at TLSSocket.emit (node:events:531:35)
                            at Socket._onTimeout (node:net:590:8)
                            at listOnTimeout (node:internal/timers:573:17)
2024-07-07 04:35:08 [I] market └ Completed in 4m 8s
2024-07-07 04:35:08 [W] market Failed with errors in 4m 10s

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by ilharp** [comment]
有关 Koishi 使用方面的问题可以在 [Discussions 版 的 Q&A 区](https://github.com/koishijs/koishi/discussions/categories/q-a) 提问。Issue 主要用于反馈 Koishi 本身的 bug。我已帮你移动分区。

插件市场相关的网络问题需要自行解决。如果需要更换镜像，在插件市场的插件配置中有镜像相关的配置和更换指引，可以自行操作。
