### ISSUE TITLE
Bug: 无法正确连接telegram服务器

### ISSUE THREAD

**Issue by GYF0814** [koishijs/koishi#1448]
### Describe the bug

无法正确连接telegram服务器

### Steps to reproduce

正常输入token后更改模式为polling后启动插件

### Expected behavior

正常连接telegram服务器

### Screenshots

2024-08-17 13:44:12 [W] app Error: connect ETIMEDOUT 149.154.167.220:443
                            at createConnectionError (node:net:1648:14)
                            at Timeout.internalConnectMultipleTimeout (node:net:1707:38)
                            at listOnTimeout (node:internal/timers:583:11)
                            at process.processTimers (node:internal/timers:519:7)
2024-08-17 13:44:12 [W] app Error: connect ENETUNREACH 2001:67c:4e8:f004::9:443 - Local (:::0)
                            at internalConnectMultiple (node:net:1182:16)
                            at Timeout.internalConnectMultipleTimeout (node:net:1712:5)
                            at listOnTimeout (node:internal/timers:583:11)
                            at process.processTimers (node:internal/timers:519:7)
2024-08-17 13:44:12 [W] app TypeError: fetch failed
                            at node:internal/deps/undici/undici:13178:13
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:317:19)
                            at async Proxy.<anonymous> (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:184:26)
                            at async _Internal.<computed> [as getMe] (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:70:26)
                            at async _TelegramBot.getLogin (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:940:18)
                            at async _TelegramBot.initialize (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:878:5)
2024-08-17 13:44:12 [W] app Error: fetch https://api.telegram.org/bottoken此处省略/getMe failed
                            at /koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:319:23
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async [cordis.invoke] (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:317:19)
                            at async Proxy.<anonymous> (/koishi/node_modules/@cordisjs/plugin-http/lib/index.cjs:184:26)
                            at async _Internal.<computed> [as getMe] (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:70:26)
                            at async _TelegramBot.getLogin (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:940:18)
                            at async _TelegramBot.initialize (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:878:5)

### Versions

- OS: <Debian 11>
- Platform: <Telegram>
- Node version: 
- Koishi version: <Latest>

### Additional context

在主机curl telegram显示正常 在容器内curl也正常 显示200OK 但是koishi就是无法连接 将容器的network改为host也没用

**Comment by ilharp** [comment]
有关 Koishi 使用方面的问题可以在 [Discussions 版 的 Q&A 区](https://github.com/koishijs/koishi/discussions/categories/q-a) 提问。Issue 主要用于反馈 Koishi 本身的 bug。我已帮你移动分区。

---

理论上这是由于你的网络质量不佳或配置有误导致。可以尝试禁用网络环境最外侧 DNS 服务器的 IPv6 解析后重启容器重试。

此外，如果你有在网络环境的任何地方配置代理或透明代理，请一并说明。
