### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by cxchency** [koishijs/koishi#1450]
### Describe the bug

无法使用，无法将消息写入数据库，接收到消息就报错

### Steps to reproduce

接收onebot消息

### Expected behavior

正常使用，将消息写入数据库

### Screenshots

2024-08-25 12:50:20 [W] app Error: property messages is not registered, declare it as `inject` to suppress this warning
                            at SyncChannel.ensure (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-messages\lib\channel.js:51:22)
                            at SyncChannel.queue (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-messages\lib\channel.js:39:14)
                            at #onMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-messages\lib\index.js:124:30)
                            at Object.apply (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:421:23)
                            at Proxy.dispatch (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:518:27)
                            at dispatch.next (<anonymous>)
                            at Function.from (<anonymous>)
                            at Proxy.emit (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:525:11)
                            at OneBotBot.dispatch (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:347:20)

### Versions

- OS: Windows Server 2022 Datacenter
- Platform: onebot
- Node version: 不到
- Koishi version: 4.17.11

**Comment by ilharp** [comment]
有关 Koishi 使用方面的问题可以在 [Discussions 版 的 Q&A 区](https://github.com/koishijs/koishi/discussions/categories/q-a) 提问。Issue 主要用于反馈 Koishi 本身的 bug。我已帮你移动分区。

---

提交 Issue 时请完整提交 Versions 的所有内容。该部分内容可以在 Koishi 窗口左下角直接点击得到。

---

日志中的 `[W]` 标明这条日志是一个警告，警告不影响正常使用。截取日志时请截取完整日志。

---

Koishi 仓库内只能处理 Koishi 相关的问题，插件问题请前往对应插件的仓库提交 Issue。Koishi 无法解决插件自身的问题。
