### ISSUE TITLE
Bug: TypeError: this.getIndexes is not a function

### ISSUE THREAD

**Issue by ZhuccIvan** [koishijs/koishi#1455]
### Describe the bug

只要一接收消息就报TypeError这个错误，现在日志里全是错误，而且沙盒发消息help指令不生效

TypeError: this.getIndexes is not a function
                            at SQLiteDriver.prepareIndexes (/koishi/node_modules/minato/lib/index.cjs:1928:35)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:973:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:965:5)

### Steps to reproduce

只要一接收消息就会报

### Expected behavior

插件能生效
日志只打印收到的消息

### Screenshots

![image](https://github.com/user-attachments/assets/dcf82f1d-26e4-4ca3-ba9d-d5423070104d)

![image](https://github.com/user-attachments/assets/12a2271c-e8a2-4b7c-bb9c-06ec50e421da)

### Versions

- OS: Linux version 3.10.0-1160.el7.x86_64
- Platform: 沙盒
- docker镜像：a193c3590c6c

**Comment by ZhuccIvan** [comment]
SQLiteDriver过期了，更新后好了

**Comment by 906051999** [comment]
是的，我也遇到这个问题。

更新插件database-sqlite即可
