### ISSUE TITLE
Bug: 关于yarn create koishi安装错误

### ISSUE THREAD

**Issue by yezi8430** [koishijs/koishi#1457]
### Describe the bug

未知的错误导致安装失败

### Steps to reproduce

yarn create koishi

### Expected behavior

正常安装

### Screenshots

➤ YN0000: └ Completed in 2s 263ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ yezikoishi@workspace:. doesn't provide @koishijs/loader (p60608), requested by @koishijs/plugin-hmr.
➤ YN0002: │ yezikoishi@workspace:. doesn't provide @koishijs/loader (pc5e30), requested by @koishijs/plugin-config.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 657ms
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.23.1 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0007: │ vue-demi@npm:0.14.10 [a9942] must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 4s 514ms
➤ YN0000: · Done with warnings in 7s 538ms
2024-09-13 10:42:22 [I] app Koishi/4.17.12
2024-09-13 10:42:22 [I] loader apply plugin group:entry
2024-09-13 10:42:22 [I] loader apply plugin group:server
2024-09-13 10:42:22 [I] loader apply plugin server:1pib1c
2024-09-13 10:42:22 [I] loader apply plugin group:basic
2024-09-13 10:42:22 [I] loader apply plugin commands:5ntm06
2024-09-13 10:42:22 [I] loader apply plugin help:5avnm0
2024-09-13 10:42:22 [I] loader apply plugin http:q2hn5p
2024-09-13 10:42:22 [I] loader apply plugin locales:u1rnd7
2024-09-13 10:42:22 [I] loader apply plugin proxy-agent:dyctkd
2024-09-13 10:42:22 [I] loader apply plugin rate-limit:ccq0u8
2024-09-13 10:42:22 [I] loader apply plugin telemetry:qcyp1f
2024-09-13 10:42:22 [I] loader apply plugin group:console
2024-09-13 10:42:22 [I] loader apply plugin actions:cfs6vm
2024-09-13 10:42:22 [I] loader apply plugin analytics:s09hu3
2024-09-13 10:42:22 [I] loader apply plugin config:dfeyvb
2024-09-13 10:42:22 [I] loader apply plugin console:ffnzxz
2024-09-13 10:42:22 [I] loader apply plugin dataview:lkd7rs
2024-09-13 10:42:22 [I] loader apply plugin explorer:msqhty
2024-09-13 10:42:22 [I] loader apply plugin logger:dntsry
2024-09-13 10:42:22 [I] loader apply plugin insight:g6w2rk
2024-09-13 10:42:22 [I] loader apply plugin market:szwyaj
2024-09-13 10:42:22 [I] loader apply plugin notifier:3fn3gj
2024-09-13 10:42:22 [I] loader apply plugin oobe:o3o26y
2024-09-13 10:42:22 [I] loader apply plugin sandbox:vc9vil
2024-09-13 10:42:22 [I] loader apply plugin status:w30lmu
2024-09-13 10:42:22 [I] loader apply plugin theme-vanilla:3ledko
2024-09-13 10:42:22 [I] loader apply plugin group:storage
2024-09-13 10:42:22 [I] loader apply plugin database-sqlite:kxt76t
2024-09-13 10:42:22 [I] loader apply plugin assets-local:srglj3
2024-09-13 10:42:22 [I] loader apply plugin group:adapter
2024-09-13 10:42:22 [I] assets missing config "selfUrl", fallback to "file:" scheme
2024-09-13 10:42:23 [E] app TypeError: Can not repeat "0" without a prefix and suffix
                            at tokensToRegexp (D:\koishi-ddnet\yezikoishi\node_modules\path-to-regexp\dist\index.js:380:31)
                            at stringToRegexp (D:\koishi-ddnet\yezikoishi\node_modules\path-to-regexp\dist\index.js:346:12)
                            at pathToRegexp (D:\koishi-ddnet\yezikoishi\node_modules\path-to-regexp\dist\index.js:422:12)
                            at new Layer (D:\koishi-ddnet\yezikoishi\node_modules\@koa\router\lib\layer.js:43:17)
                            at Router.register (D:\koishi-ddnet\yezikoishi\node_modules\@koa\router\lib\router.js:570:17)
                            at Server.register (D:\koishi-ddnet\yezikoishi\node_modules\@cordisjs\plugin-server\lib\index.cjs:199:25)
                            at Router.<computed> [as get] (D:\koishi-ddnet\yezikoishi\node_modules\@koa\router\lib\router.js:200:12)
                            at NodeConsole.serveAssets (D:\koishi-ddnet\yezikoishi\node_modules\@koishijs\plugin-console\lib\node\index.js:145:21)
                            at NodeConsole.start (D:\koishi-ddnet\yezikoishi\node_modules\@koishijs\plugin-console\lib\node\index.js:106:10)
                            at D:\koishi-ddnet\yezikoishi\node_modules\@cordisjs\core\lib\index.cjs:1199:18
2024-09-13 10:42:23 [I] server server listening at http://127.0.0.1:5140
2024-09-13 10:42:23 [I] sqlite auto creating table user
2024-09-13 10:42:23 [I] sqlite auto creating table binding
2024-09-13 10:42:23 [I] sqlite auto creating table channel
2024-09-13 10:42:23 [S] telemetry
                        欢迎使用 Koishi！

### Versions

- OS: 
- Platform: 
- Node version: <22.8.0>
- Koishi version: <4.17.12>

**Comment by yezi8430** [comment]
虽然说已经有提示语了，但是打开localhost:5140会只显示not found

**Comment by MaikoTan** [comment]
As a temporary solution, add these lines to the `package.json` at the root of your project:

```json
  "resolution": {
    "path-to-regexp": "^6.2.2 <6.3.0"
  }
```

Reference: https://github.com/cordiverse/cordis/issues/15

**Comment by yezi8430** [comment]
> **临时**解决方案，提出以下作为添加到项目`package.json`根目录中：
> 
> ```json
>   "resolution": {
>     "path-to-regexp": "^6.2.2 <6.3.0"
>   }
> ```
> 
> 参考：[cordiverse/cordis#15](https://github.com/cordiverse/cordis/issues/15)

![image](https://github.com/user-attachments/assets/e0e80d08-dbfc-459c-badf-ef8d7b25277c)
请问我加的位置不对吗，似乎没有生效

**Comment by MaikoTan** [comment]
> 请问我加的位置不对吗，似乎没有生效

Oh, you'd need to run `yarn` after the appending. Sorry for forgetting to say that.

**Comment by yezi8430** [comment]
> > 请问我加的位置不对吗，好像没有生效
> 
> 哦，你需要`yarn`在附加后运行。抱歉，我忘了说了。
> 
> 此外，这只是一个**临时的**修复，我们目前正在调查这个问题。

感谢你的帮助
