### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by XxLittleCxX** [koishijs/koishi#155]
**Describe the bug**

```
[W] command before command: [removed]
     TypeError: Cannot read property 'includes' of undefined
         at _Session.<anonymous> (/dev/null/node_modules/koishi-core/src/command.ts:288:35)
         at _App.serial (/dev/null/node_modules/koishi-core/src/context.ts:269:37)
```

**To Reproduce**
Unknown.

**Expected behavior**
It works

**Versions**

- OS: Ubuntu 18.04.5 LTS x86_64
- Node Version: v14.4.0
- Koishi Version: 3.2.0

**Comment by undefined-moe** [comment]
koishi-plugin-schedule interval event
