### ISSUE TITLE
onebot 中 bot.$sendGroupNotice 似乎出现问题

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#191]
**Describe the bug**

RT

**To Reproduce**

假定一个最简单的指令：

```js
App.platform('onebot')
  .group()
  .command('announcement <content:text>', '', { authority: 3 })
  .action(async ({ session }, content) => {
    if (!content) return
    await session.bot.$sendGroupNotice(session.groupId, content)
  })
```

发送：`announcement 群公告`

报错：

```
SenderError: Error when trying to send to send_group_notice, args: {"group_id":"123456","content":"群公告"}, retcode: 404
    at CQBot.get (C:\QQbot-SILI\node_modules\koishi-adapter-onebot\dist\index.js:314:13)
        -> (C:\QQbot-SILI\node_modules\koishi-adapter-onebot\src\bot.ts:79:13)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async CQBot.<computed> [as $sendGroupNotice] (C:\QQbot-SILI\node_modules\koishi-adapter-onebot\dist\index.js:417:18)
        -> (C:\QQbot-SILI\node_modules\koishi-adapter-onebot\src\bot.ts:200:18)
```

**Expected behavior**

可以发送群公告

**Screenshots**

**Versions**

- Node Version: [e.g. 10.16.0]
- CQHTTP Version: v0.9.40-fix3 (websocket)
- koishi: ^3.5.1
- adapter-onebot: ^3.0.0

**Additional context**

**Comment by Shigma** [comment]
不如等 go-cqhttp 更新吧？

**Comment by Dragon-Fish** [comment]
> 不如等 go-cqhttp 更新吧？

= =

**Comment by Dragon-Fish** [comment]
「漫长的岁月里，我一直在等待……」—— 机智的小鱼君

**Comment by Shigma** [comment]
问了下 go-cqhttp 那边，似乎不打算改。那我下个版本就改吧。

**Comment by Dragon-Fish** [comment]
reply  「……那一位手持koishi牌啤酒的大英雄，Shigma」—— 机智的小鱼君
