### ISSUE TITLE
使用websocket报错

### ISSUE THREAD

**Issue by Anillc** [koishijs/koishi#29]
**Describe the bug**
我在创建koishi机器人的时候使用想使用websocket，但是无论是使用cli还是调用koishi都会报错，而使用post的方式就没有问题，请问是bug还是对websocket支持还没有完善

**To Reproduce**
使用cli的ws选项或者直接调用都会出现这种情况

**Expected behavior**
正常启动

**Screenshots**
```
error TypeError: Cannot destructure property 'pluginMajorVersion' of 'this.version' as it is undefined.
    at WsClient.versionLessThan (/data/data/com.termux/files/home/kbot/node_modules/koishi-core/dist/server.js:176:17)
    at WsClient.listen (/data/data/com.termux/files/home/kbot/node_modules/koishi-core/dist/server.js:186:22)
```

**Versions**

- OS: Android 10 termux和CentOS 7上都试过了
- Node Version: 12.16.1 和 13.6.0
- CoolQ Version: 5.15.9
- CQHTTP Version: 4.14.1
- Koishi Version: 1.11.1

**Additional context**

**Comment by Shigma** [comment]
谢谢反馈！

这是一个已知 bug，是由于 Koishi 没有支持 CQHTTP 4.14 新引入的 connect 事件引起的。预计最近两天就会发布新的版本解决这个问题。在此之前如果要调试可以先使用 http 模式或使用 CQHTTP 4.13。

**Comment by kou-yi** [comment]
好的，谢谢

**Comment by masnn** [comment]
The same as above.

```
Unhandled Rejection: Promise {
  <rejected> TypeError: Cannot destructure property `pluginMajorVersion` of 'undefined' or 'null'.
      at WsClient.versionLessThan (/bot/node_modules/koishi-core/dist/server.js:176:85)
      at WsClient.listen (bot/node_modules/koishi-core/dist/server.js:186:22)
      at process._tickCallback (internal/process/next_tick.js:68:7) } 
```

**Comment by Shigma** [comment]
@Anillc @masnn 刚刚发布了 Koishi 1.11.2，应该解决了这个问题。

**Comment by masnn** [comment]
Problem fixed. Thank you!
