### ISSUE TITLE
Bug: database-mongo@next 的一些故障

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#417]
### Describe the bug

当使用 database-mongo 时，似乎存在以下问题：

1. 新增的 user/channel 无法自动入库，导致不应答新用户/群聊（报错见下文）
2. 自增键的类型存在问题，类型被错误的设置为了字符串，导致自增主键形如 "1" "11" "111"

### Steps to reproduce

1. 初始化一个 koishi v4 实例
2. 加载插件 database-mongo
3. bot 收到任意消息
4. see errors

### Expected behavior

-

### Screenshots

```
    Error: cannot observe null or undefined
        at observe (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+utils@5.0.0-beta.1\node_modules\@koishijs\utils\lib\node.js:677:11)
            -> (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+utils@5.0.0-beta.1\node_modules\@koishijs\utils\src\observe.ts:122:11)
        at Session.observeChannel (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+core@4.0.0-beta.3\node_modules\@koishijs\core\lib\node.js:1086:50)
            -> (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+core@4.0.0-beta.3\node_modules\@koishijs\core\src\session.ts:245:24)
        at processTicksAndRejections (node:internal/process/task_queues:93:5)
        at async _App._process (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+core@4.0.0-beta.3\node_modules\@koishijs\core\lib\node.js:2450:25)
            -> (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+core@4.0.0-beta.3\node_modules\@koishijs\core\src\app.ts:163:25)
        at async next (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+core@4.0.0-beta.3\node_modules\@koishijs\core\lib\node.js:2512:16)
            -> (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+core@4.0.0-beta.3\node_modules\@koishijs\core\src\app.ts:237:16)
        at async _App._handleMessage (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+core@4.0.0-beta.3\node_modules\@koishijs\core\lib\node.js:2525:5)
            -> (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+core@4.0.0-beta.3\node_modules\@koishijs\core\src\app.ts:248:5)
        at async Promise.all (index 0)
        at async _Context.parallel (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+core@4.0.0-beta.3\node_modules\@koishijs\core\lib\node.js:1751:5)
            -> (C:\Chatbot-SILI\node_modules\.pnpm\registry.npmmirror.com+@koishijs+core@4.0.0-beta.3\node_modules\@koishijs\core\src\context.ts:328:5)Middleware stack:
```

### Versions

- OS: 
- Platform: 
- Node version: 14.x
- "koishi": "^4.0.0-beta.3"
- "@koishijs/plugin-database-mongo": "^3.0.0-beta.2"

**Comment by Shigma** [comment]
问题 2 已修复，问题 1 暂时没有复现，不知道是不是因为 2 已修复的原因，发版后麻烦再次测试一下，谢谢了。
