### ISSUE TITLE
Bug: schedule 出错

### ISSUE THREAD

**Issue by XxLittleCxX** [koishijs/koishi#459]
### Describe the bug

执行的sql是这样的

```sql
SELECT  FROM channel _channel WHERE `platform` = 'onebot' AND `id` = '12345678'
```

```
Trace: onebot 12345678 []
    at MysqlDatabase.getChannel (/dev/random/node_modules/@koishijs/core/src/database.ts:90:11)
    at Session.getChannel (/dev/random/node_modules/@koishijs/core/src/session.ts:204:25)
    at Session.observeChannel (/dev/random/node_modules/@koishijs/core/src/session.ts:235:28)
    at Session.execute (/dev/random/node_modules/@koishijs/core/src/session.ts:362:18)
    at null.executeSchedule (/dev/random/node_modules/@koishijs/plugin-schedule/src/index.ts:65:12)
    at null.<anonymous> (/dev/random/node_modules/@koishijs/plugin-schedule/src/index.ts:97:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce

schedule

### Expected behavior

it works

### Versions

latest

**Comment by Shigma** [comment]
执行的具体指令是什么

**Comment by XxLittleCxX** [comment]
自己写的一个（

**Comment by Shigma** [comment]
那给我能复现的例子

**Comment by XxLittleCxX** [comment]
我这很神秘

```
import { Context } from "koishi";

export async function apply(ctx: Context) {
  ctx.command("test", { authority: 2 })
    .action(() => 'success')
}
```

```
schedule 1m / 1m -- test
```

添加后是能跑的，然后重启的话必炸，错误如上

**Comment by XxLittleCxX** [comment]
你试试能不能复现

**Comment by Shigma** [comment]
有点迷惑，我这不能复现你的情况，但是我遇到了重开后失效的问题，也就是添加的日程存在但是不执行。

这个问题在于 bot 初始化可能早于或晚于数据库初始化。所以甚至不能稳定出发。正在尝试修改 schedule 的执行策略。
