### ISSUE TITLE
配置 MySQL 后无法启动

### ISSUE THREAD

**Issue by Clansty** [koishijs/koishi#48]
在配置文件中配置 MySQL 后无法启动机器人

```js
module.exports = {
  type: "http",
  port: 8080,
  server: "http://localhost:5700",
  plugins: [

  ],
  database: {
    mysql: {
      host: 'x.x.x.x',
      port: 3306,
      user: 'root',
      password: 'xxxxxx',
      database: 'xxx',
    },
  }, 
}
```

错误信息
```
error TypeError: Cannot read property '0' of undefined
    at loadEcosystem (/usr/local/lib/node_modules/koishi/dist/worker.js:65:72)
    at prepareApp (/usr/local/lib/node_modules/koishi/dist/worker.js:92:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/koishi/dist/worker.js:111:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

- OS: Ubuntu 20.04
- Node Version: 10.19.0
- CoolQ Version: 5.15.10
- CQHTTP Version: 4.15.0
- Koishi Version: 1.12.0

**Comment by Clansty** [comment]
加载了任何插件也都启动不了，包括默认的 common

**Comment by Clansty** [comment]
换了别的服务器/操作系统依然未解决

玄学问题

**Comment by Clansty** [comment]
编译安装 node 14.5.0 可以解决
