### ISSUE TITLE
中间件对群消息不执行

### ISSUE THREAD

**Issue by Clansty** [koishijs/koishi#49]
**Describe the bug**
中间件对群消息不执行

**To Reproduce**
···
app.middleware((meta, next) => {
        console.log(meta)
        return next()
    })
···
对群发送一条消息

**Expected behavior**

日志输出 meta 对象

**Versions**

- OS: Debian 10
- Node Version: 14.5.0
- CoolQ Version: Air
- CQHTTP Version: 4.15.0
- Koishi Version: 1.12.0

**Additional context**

这 SDK 是先有文档再有程序的吧

**Comment by Shigma** [comment]
首先感谢您的反馈。

如果 SDK 无法运行那确实抱歉，但是这个 SDK 已经在我手上稳定运行了一年，如果不是想开源我也不会写这些文档，自然也不会存在现有文档再有程序的问题。您使用的 Koishi 1.12.0 已经发版数月，而之前的其他 issue 没有提及这个问题，说明可能是您的操作失误或个别案例。

最近我忙于学业和下个版本的开发，可能暂时无暇给予立即的回应，对此深表遗憾。周末我会尝试复现您所描述的问题。

**Comment by Clansty** [comment]
谢谢，我昨天晚上想了一下，可能是数据库的问题。因为最近与数据库有关的模块存在很多不稳定的情况

**Comment by Clansty** [comment]
不是数据库的问题

请问作者稳定使用的 nodejs 和 CQHTTP 是什么版本呢

**Comment by Clansty** [comment]
···
(node:433) UnhandledPromiseRejectionWarning: TypeError: this.database.observeGroup is not a function
    at App._attachGroup (/home/lw/tianlang/node_modules/koishi-core/dist/app.js:421:43)
    at Array.App._preprocess (/home/lw/tianlang/node_modules/koishi-core/dist/app.js:151:46)
    at next (/home/lw/tianlang/node_modules/koishi-core/dist/app.js:226:96)
    at EventEmitter.App._applyMiddlewares (/home/lw/tianlang/node_modules/koishi-core/dist/app.js:233:19)
    at EventEmitter.emit (events.js:315:20)
    at App.emitEvent (/home/lw/tianlang/node_modules/koishi-core/dist/app.js:407:30)
    at HttpServer.dispatchMeta (/home/lw/tianlang/node_modules/koishi-core/dist/server.js:166:17)
    at IncomingMessage.<anonymous> (/home/lw/tianlang/node_modules/koishi-core/dist/server.js:259:22)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
(node:433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
···

**Comment by simon300000** [comment]
不知道koishi有没有debug模式，打开了就可以把所有东西都输出到控制台
