### ISSUE TITLE
Bug: 在使用 js/ts config 文件时，watch 热插拔功能报错

### ISSUE THREAD

**Issue by canisminor1990** [koishijs/koishi#526]
### Describe the bug

在使用 js/ts config 文件时，watch 热插拔功能报错，yml 格式的配置文件正常。

```
[W] app TypeError: Cannot read properties of undefined (reading 'dirname')
        at Watcher.start (/Users/canisminor/canisminor-bot/node_modules/@koishijs/cli/src/addons/watcher.ts:78:32)
        at /Users/canisminor/canisminor-bot/node_modules/@koishijs/cli/src/addons/watcher.ts:71:32
        at App.start (/Users/canisminor/canisminor-bot/node_modules/@koishijs/core/src/app.ts:94:25)
        at App.import_core6.App.start (/Users/canisminor/canisminor-bot/node_modules/koishi/src/index.ts:68:16)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce

在使用 js/ts config 文件时，watch 热插拔功能报错，yml 格式的配置文件正常，经测试 cli 中的 loader 注入失败，对象丢失。

### Expected behavior

热重载

### Screenshots

```
[W] app TypeError: Cannot read properties of undefined (reading 'dirname')
        at Watcher.start (/Users/canisminor/canisminor-bot/node_modules/@koishijs/cli/src/addons/watcher.ts:78:32)
        at /Users/canisminor/canisminor-bot/node_modules/@koishijs/cli/src/addons/watcher.ts:71:32
        at App.start (/Users/canisminor/canisminor-bot/node_modules/@koishijs/core/src/app.ts:94:25)
        at App.import_core6.App.start (/Users/canisminor/canisminor-bot/node_modules/koishi/src/index.ts:68:16)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Versions

- OS: MacOS
- Platform: onebot
- Node version: 16.13.1
- Koishi version: 4.2.1

**Comment by Shigma** [comment]
感谢反馈，此问题属实，将在 4.3 版本修复。
