### ISSUE TITLE
Bug: console 设为 devMod 以后报错缺少 ansi_up

### ISSUE THREAD

**Issue by DDEle** [koishijs/koishi#542]
### Describe the bug

如题

### Steps to reproduce

如题

### Expected behavior

能正常使用开发模式的控制台

### Screenshots

```
[W] app Error: Failed to resolve force included dependency: ansi_up
        at optimizeDeps (full\path\to\project\node_modules\vite\src\node\optimizer\index.ts:196:17)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async runOptimize (full\path\to\project\node_modules\vite\src\node\server\index.ts:533:40)
        at async createServer (full\path\to\project\node_modules\vite\src\node\server\index.ts:560:5)
        at async HttpService.createVite (full\path\to\project\node_modules\@koishijs\plugin-console\src\http.ts:121:17)  
        at async HttpService.start (full\path\to\project\node_modules\@koishijs\plugin-console\src\http.ts:30:30)        
        at async full\path\to\project\node_modules\@koishijs\core\src\database.ts:55:7
        at async Promise.all (index 7)
        at async TaskQueue.flush (full\path\to\project\node_modules\@koishijs\core\src\app.ts:322:7)
        at async App.start (full\path\to\project\node_modules\@koishijs\core\src\app.ts:97:5)
```

### Versions

非官仓调试
- OS: Windows 10
- Node version:  v16.13.1
- Koishi version: 4.3.1

### Additional context

手动添加依赖以后网页会白屏 网页控制台报错
```
Uncaught SyntaxError: The requested module '/vite/@fs/full/path/to/project/node_modules/dayjs/dayjs.min.js?v=7b50d697' does not provide an export named 'default'
```

**Comment by Shigma** [comment]
这个问题应该已经修复，请用最新版本确认一下。

**Comment by DDEle** [comment]
确实不会少 ansi_up 了 但是还是白屏
