### ISSUE TITLE
Bug(database-mongo): error when using mongodb+srv protocol

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/koishi#629]
### Describe the bug

When setting the protocol of `database-mongo` plugin, it would report error that says `mongodb+srv` URI cannot have port number.

### Steps to reproduce

1. touch koishi.config.yml
2. add `database-mongo` section with protocol set to `mongodb+srv`
3. install all the stuff
4. `koishi start`
5. ERROR!

### Expected behavior

Obviously be able to use the plugin normally.

### Screenshots

```
 [W] app MongoParseError: mongodb+srv URI cannot have port number
         at new ConnectionString (/app/node_modules/mongodb-connection-string-url/lib/index.js:146:23)
         at parseOptions (/app/node_modules/mongodb/lib/connection_string.js:213:17)
         at new MongoClient (/app/node_modules/mongodb/lib/mongo_client.js:62:63)
         at Function.connect (/app/node_modules/mongodb/lib/mongo_client.js:184:33)
         at MongoDriver.start (/app/node_modules/@cosmotype/driver-mongo/lib/index.js:30:51)
         at /app/node_modules/@koishijs/plugin-database-mongo/lib/index.js:45:32
         at App.start (/app/node_modules/@koishijs/core/lib/node.js:2624:25)
         at import_core6.App.start (/app/node_modules/koishi/lib/index.js:408:16)
         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Versions

- OS:  Ubuntu 20.04
- Platform:  Any
- Node version:  16.18.0
- Koishi version:  4.5.2
- `database-mongo` version: 3.1.2

**Comment by MaikoTan** [comment]
Looks like set the port as 0 would solve the problem, but I hope there is a comprehensive solution.

**Comment by Shigma** [comment]
This is probably a regression issue. 🤣 

So will checking the value of `protocol` and ignore `port` if `srv` is included solve the problem?

**Comment by MaikoTan** [comment]
Are there only "mongodb+srv" protocol that requires no port in URI? If ture, I think it is ok to do the such checking.

**Comment by MaikoTan** [comment]
Wonderful ☺️
\夢夢/
