### ISSUE TITLE
Bug: 按照教程构建start报错

### ISSUE THREAD

**Issue by nyakochanNeee** [koishijs/koishi#696]
### Describe the bug

2022-05-26 02:37:50 [I] app Koishi/4.7.1
2022-05-26 02:37:50 [E] app TypeError: this.caller.lifecycle.checkLength is not a function
                            at Internal.middleware (C:\Users\CuteFox\Desktop\forkBot-master\node_modules\@koishijs\core\lib\node.js:2038:27)
                            at new Internal (C:\Users\CuteFox\Desktop\forkBot-master\node_modules\@koishijs\core\lib\node.js:2020:10)
                            at new App (C:\Users\CuteFox\Desktop\forkBot-master\node_modules\cordis\lib\index.cjs:489:19)
                            at Loader.createApp (C:\Users\CuteFox\Desktop\forkBot-master\node_modules\@koishijs\cli\lib\worker\index.js:284:29)
                            at Object.<anonymous> (C:\Users\CuteFox\Desktop\forkBot-master\node_modules\@koishijs\cli\lib\worker\index.js:595:18)
                            at Module._compile (node:internal/modules/cjs/loader:1105:14)
                            at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
                            at Module.load (node:internal/modules/cjs/loader:981:32)
                            at Function.Module._load (node:internal/modules/cjs/loader:822:12)
                            at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

### Steps to reproduce

npm install
npm start

### Expected behavior

huh?

### Screenshots

![image](https://user-images.githubusercontent.com/100355329/170347117-fa592293-9988-4482-861c-838f4592b50d.png)

### Versions

- OS: Windows 10
- Platform: None
- Node version: 16.15.0
- Koishi version: 4.7.1

**Comment by shigma** [comment]
非常抱歉！我今天下午疏忽推了一个不兼容的版本导致了你的问题。

你可以使用以下方式解决：

1. 进入你生成的目录
2. 打开 package.json 并添加以下内容：

```diff
  },
+ "resolutions": {
+   "cordis": "~1.1.0"
+ },
  "yakumo": {
```

3. 打开命令行并输入 `yarn`。
4. 运行完成后再次 `yarn start` 启动。

如果仍有问题可以继续回复或者加群解决，群号在 readme 底部和文档右上角。

**Comment by shigma** [comment]
此外，Koishi 4.7.2 版本将解决这个问题。新版本发布时我会在这个 issue 通知。届时即可删掉这三行内容。

**Comment by nyakochanNeee** [comment]
![image](https://user-images.githubusercontent.com/100355329/170355431-6c528247-0f58-4b42-8e37-59ab7901aab9.png)
是这样添加吗

**Comment by nyakochanNeee** [comment]
![image](https://user-images.githubusercontent.com/100355329/170356312-b0c4f512-de3b-43d5-ad8d-b8576cf3cd99.png)
还是有一些问题 ;w;

**Comment by nyakochanNeee** [comment]
使用yarn start 已解决
