### ISSUE TITLE
Bug: `help` 会导致 `hitokoto` 和 `music` 插件报错终止

### ISSUE THREAD

**Issue by ilharp** [koishijs/koishi#702]
### Describe the bug

```
6|harperne | 2022-05-28 17:47:33 [I] app apply plugin help
6|harperne | 2022-05-28 17:47:33 [E] app Error: duplicate option name "h" for command "music"
6|harperne |                             at _Command._assignOption (/files/proj/harperneko/node_modules/@koishijs/core/src/command/parser.ts:450:17)
6|harperne |                             at _Command._createOption (/files/proj/harperneko/node_modules/@koishijs/core/src/command/parser.ts:440:12)
6|harperne |                             at _Command.option (/files/proj/harperneko/node_modules/@koishijs/core/src/command/command.ts:185:10)
6|harperne |                             at null.enableHelp (/files/proj/harperneko/node_modules/@koishijs/plugin-help/src/index.ts:27:14)
6|harperne |                             at _Command.use (/files/proj/harperneko/node_modules/@koishijs/core/src/command/command.ts:225:12)
6|harperne |                             at null.<anonymous> (/files/proj/harperneko/node_modules/@koishijs/plugin-help/src/index.ts:43:49)
6|harperne |                             at Map.forEach (<anonymous>)
6|harperne |                             at Object.apply (/files/proj/harperneko/node_modules/@koishijs/plugin-help/src/index.ts:43:30)
6|harperne |                             at Runtime.Runtime.apply (/files/proj/harperneko/node_modules/cordis/src/plugin.ts:147:21)
6|harperne |                             at Runtime.callback (/files/proj/harperneko/node_modules/cordis/src/plugin.ts:166:14)
6|harperne | error Command failed with exit code 1.
```

### Steps to reproduce

在 4.7.2 安装 `help` 和 `music` 插件

### Expected behavior

1

### Versions

```
# uname -a
Linux VM-4-12-ubuntu 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
# node -v
v16.13.1
# yarn koishi -v
yarn run v1.22.17
$ koishi -v
koishi/4.7.0 linux-x64 node-v16.13.1
```

**Comment by shigma** [comment]
![image](https://user-images.githubusercontent.com/33423008/170823722-ffc78725-4216-4ba6-a4c5-da3bfcfa2a88.png)

未复现此问题。

**Comment by shigma** [comment]
![image](https://user-images.githubusercontent.com/33423008/170823918-1f925f5c-a2e7-4109-bcac-9751ece09b4f.png)

两个插件均未复现。
