### ISSUE TITLE
Bug:无法在discord发送图片

### ISSUE THREAD

**Issue by TZFC** [koishijs/koishi#822]
### Describe the bug

更新至 @koishijs/plugin-adapter-discord 3.2.6 之后，无法在discord发送图片。
log:
[38;5;8m2022-10-17 15:40:13[0m [W] [38;5;129;1msession[0m TypeError: this.bot.ctx.http.file is not a function
                            at Sender.sendAsset (C:\Users\Administrator\Downloads\koishi-desktop-win-x64-v0.6.3\data\instances\default\node_modules\@satorijs\adapter-discord\lib\index.js:250:46)

### Steps to reproduce

@koishijs/plugin-adapter-discord 3.2.6
koishi-plugin-novelai 1.10.1
在discord中发送 “约稿 cat”
回复中只得到文字，没有图片

### Expected behavior

在曾经的版本中，会得到koishi-plugin-novelai 的所有返回结果，文字+图片。

### Screenshots

log:
[38;5;8m2022-10-17 15:40:13[0m [W] [38;5;129;1msession[0m TypeError: this.bot.ctx.http.file is not a function
                            at Sender.sendAsset (C:\Users\Administrator\Downloads\koishi-desktop-win-x64-v0.6.3\data\instances\default\node_modules\@satorijs\adapter-discord\lib\index.js:250:46)

### Versions

- OS:  Windows Server 2022 Datacenter 21H2
- Platform:  Discord
- Node version:  
- Koishi version: 4.9.5

**Comment by shigma** [comment]
更新版本的时候出了点问题。如果你会弄的话可以通过 resolutions 解决。

```json
{
  "resolutions": {
    "@satorijs/core": "1.2.5",
    "@satorijs/satori": "1.2.5"
  }
}
```

将上述代码加入 package.json 文件，并重新 yarn 可以解决。

我们在会在未来三天内发布新的版本 4.9.6，届时直接更新也可以解决。

**Comment by shigma** [comment]
最新版已经修复此问题。
