### ISSUE TITLE
Bug: 自建插件按照指南里执行指令代码运行报TypeError: Cannot read properties of undefined (reading 'getConfig')

### ISSUE THREAD

**Issue by dalamudx** [koishijs/koishi#830]
### Describe the bug

自建插件按照指南里执行指令代码运行报TypeError: Cannot read properties of undefined (reading 'getConfig')

### Steps to reproduce

自建插件
yarn setup xxxx -c
index.ts部分代码
```
import { Context, Dict, Logger, Schema, Session } from 'koishi'
import { resolve } from 'path'
import { } from '@koishijs/plugin-console'
import { } from '@koishijs/plugin-echo'
const logger = new Logger('news')
export const name = 'xxxx'
export function apply(ctx: Context) {
  ctx.middleware((session, next) => {
    if (session.content === '查看帮助') {
      return session.execute('help', next)
    } else {
      return next()
    }
  })
}
```
启动插件后，如果rate limit也是启动状态，控制台日志会抛出以下报错
```
TypeError: Cannot read properties of undefined (reading 'getConfig')
                            at bypassRateLimit (/data/koishi-app/node_modules/@koishijs/plugin-rate-limit/src/index.ts:64:50)
                            at Session2.<anonymous> (/data/koishi-app/node_modules/@koishijs/plugin-rate-limit/src/index.ts:71:9)
                            at Lifecycle.serial (/data/koishi-app/node_modules/cordis/src/events.ts:108:37)
                            at Context2.<anonymous> (/data/koishi-app/node_modules/cordis/src/context.ts:74:27)
                            at _Command._checkers (/data/koishi-app/node_modules/@koishijs/core/src/command/command.ts:51:21)
                            at _Command.execute (/data/koishi-app/node_modules/@koishijs/core/src/command/command.ts:240:38)
                            at <anonymous> (/data/koishi-app/node_modules/@koishijs/core/src/session.ts:324:36)
                            at Session2.withScope (/data/koishi-app/node_modules/@koishijs/core/src/session.ts:207:20)
                            at Session2.execute (/data/koishi-app/node_modules/@koishijs/core/src/session.ts:323:17)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                        Middleware stack:
                          - /data/koishi-app/node_modules/@koishijs/plugin-forward/src/index.ts:110:41
                          - /data/koishi-app/node_modules/@koishijs/plugin-suggest/src/index.ts:89:78
                          - /data/koishi-app/node_modules/@koishijs/core/src/internal.ts:76:50
                          - /data/koishi-app/node_modules/@koishijs/core/src/internal.ts:168:12
                          - /data/koishi-app/node_modules/@koishijs/plugin-auth/src/index.ts:147:16
```
如果闭关rate limit插件重新执行指令会恢复正常

### Expected behavior

能够在rate limit启用状态下正常执行指令

### Versions

- OS: Ubuntu 22.04.1 LTS
- Platform: Discord & Onebot
- Node version: v16.18.0
- Koishi version: 4.9.6
- Plugin rate limit version: 1.2.2

**Comment by shigma** [comment]
应该是 rate-limit 的 bug，预计将于 4.10.1（本周内）修复。

**Comment by shigma** [comment]
@koishijs/plugin-rate-limit 最新版 1.2.3 应该修复了此问题。
