### ISSUE TITLE
Koishi v2 提问楼

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#85]
具体404了的链接是 https://koishi.js.org/v1/

另外测试了一下当前（2020/8/19 20:00）npm i koishi@next，配置如下

```javascript
const bot = new App({
  type: 'ws',
  port: 8080,
  server: 'http://localhost:6700'
});
```

结果运行脚本时弹出以下错误信息：
```
Error: unsupported type "ws", you should import the adapter yourself
    at new App (E:\dev\qqbot\node_modules\koishi-core\dist\app.js:52:19)
    at Object.<anonymous> (E:\dev\qqbot\index.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qqbot@1.0.0 bot: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the qqbot@1.0.0 bot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
不知道是什么原因导致的……

结果导致目前v1和v2两边都不太能用……

**Comment by idlist** [comment]
啊这，现在v1文档又好了

**Comment by masnn** [comment]
建议直接使用@next （？

**Comment by Shigma** [comment]
@idlist v2 的文档还在开发中，很多变动没有写上，抱歉。

```ts
const { App } = require('koishi')
require('koishi-adapter-cqhttp')

const bot = new App({
  type: 'cqhttp:ws',
  port: 8080,
  server: 'http://localhost:6700'
});
```

**Comment by dzcpy** [comment]
想请教下v2怎样主动发送消息？bot.sender 提示不存在

**Comment by masnn** [comment]
把sender去掉，直接bot.sendGroupMsg

**Comment by Shigma** [comment]
> 想请教下v2怎样主动发送消息？bot.sender 提示不存在

```js
ctx.bot[selfId].sendGroupMsg()
session.$bot.sendGroupMsg()
session.$send()
```

**Comment by Shigma** [comment]
这个 issue 先关了，如果有问题欢迎另开 issue~
