### ISSUE TITLE
Bug: koishi启动时出现错误(Debian 11)

### ISSUE THREAD

**Issue by nrxboat** [koishijs/koishi#943]
### Describe the bug

使用npm start命令启动（安装koishi后的首次启动）时出现报错现象，且访问对应端口未能显示控制台

### Steps to reproduce

Debian11下按照“创建模板项目”中的“使用包管理器创建”部署koishi，然后使用npm start启动

另外在replit这个平台上部署时也存在这个问题

### Expected behavior

控制台正常显示

### Screenshots

以下为安装koishi时出现的异常日志：
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

以下为koishi启动时的部分异常日志：
2023-01-20 05:44:27 [W] assets missing configuration "selfUrl", fallback to "file:" scheme2023-01-20 05:44:27 [I] app server listening at http://localhost:5140
2023-01-20 05:44:33 [W] market timeout of 5000ms exceeded
2023-01-20 05:44:33 [W] market timeout of 5000ms exceeded
2023-01-20 05:44:58 [W] market AxiosError: timeout of 30000ms exceeded
                            at RedirectableRequest.handleRequestTimeout (/root/koishi-bot/node_modules/axios/dist/node/axios.cjs:2504:16)
                            at RedirectableRequest.emit (node:events:513:28)
                            at Timeout.<anonymous> (/root/koishi-bot/node_modules/follow-redirects/index.js:169:12)
                            at listOnTimeout (node:internal/timers:564:17)
                            at process.processTimers (node:internal/timers:507:7)

### Versions

- OS: Debian 11 
- Platform: 尚未部署 
- Node version: 18.13.0LTS 
- Koishi version:  5.2.7

**Comment by ilharp** [comment]
此错误是网络质量原因所致，你的网络环境无法连接到 Koishi 的插件市场。Koishi 插件市场之外的其他功能仍然可用。

**Comment by nrxboat** [comment]
> 此错误是网络质量原因所致，你的网络环境无法连接到 Koishi 的插件市场。Koishi 插件市场之外的其他功能仍然可用。

vps区域和replit均位于国外，推测应该不是这个原因
另外可能是我的描述有点问题，我再改改描述

**Comment by ilharp** [comment]
Koishi 插件市场默认使用大陆镜像源，国外无法连接是预期的。你可以修改 `.env` 文件和 market 插件的配置以选择离你所在地区最近的镜像。

**Comment by nrxboat** [comment]
尝试修改.env后发现问题仍然存在，问题应该不在于网络问题
log中虽显示了成功监听端口，但实际上无法打开控制台
在已提交的日志中
2023-01-20 05:44:27 [W] assets missing configuration "selfUrl", fallback to "file:"
这条日志可能能够反映出现问题的原因


网上搜了一下，现有的搭建教程几乎全是在windows上部署的koishi，剩下的也基本是安卓用termux建chroot容器安装的，在linux上安装koishi的例子几乎没见过

**Comment by nrxboat** [comment]
再次尝试启动koishi，结果如下：
![Screenshot_2023-01-20-23-45-23-66](https://user-images.githubusercontent.com/69232821/213742884-4f02a801-5dd5-4872-842e-83a7ca10a62a.png)

按ctrl+c后，结果如下：
![Screenshot_2023-01-20-23-45-34-20](https://user-images.githubusercontent.com/69232821/213743017-d7c1a86a-37ca-4895-ad0d-d87f53dca888.png)

**Comment by ilharp** [comment]
> 问题应该不在于网络问题

没看到「无法显示控制台」，是我的疏忽。控制台内无法显示插件市场是网络问题，无法显示控制台是因为你未按照官方文档中 [服务器部署](https://koishi.chat/manual/recipe/server.html) 的步骤操作所致。

> 这条日志可能能够反映出现问题的原因

这条日志是意图的行为，并非问题的原因。

> 网上搜了一下，现有的搭建教程几乎全是在windows上部署的koishi，剩下的也基本是安卓用termux建chroot容器安装的，在linux上安装koishi的例子几乎没见过

这是因为在 Linux 上使用 Koishi 的大多数用户遇到问题都可以自己解决，导致了互联网上在 Linux 上运行 Koishi 的资源较少的现象。Koishi 团队绝大多数成员的 Koishi 生产环境均为 Linux，Linux 在目前仍是长期稳定运行 Koishi 的最佳选择。

---

鉴于本 issue 的讨论内容并非 Koishi 的 bug，本 issue 将被锁定后移至 discussion。后续可前往对应的 discussion 继续交流，如果有其他反馈内容请创建新的 issue。
