### ISSUE TITLE
Bug: 当插件配置项为Date类型时无法启动插件

### ISSUE THREAD

**Issue by nmMmnmMmn** [koishijs/koishi#952]
### Describe the bug

若插件配置项为Date类型，设置配置项后启动插件时会报错

```
[W] app TypeError: expected Date | string but got {}
                            at <anonymous> (D:\dev\genshin-bot\node_modules\.pnpm\schemastery@3.6.1\node_modules\schemastery\src\index.ts:423:9)
                            at Function.resolve (D:\dev\genshin-bot\node_modules\.pnpm\schemastery@3.6.1\node_modules\schemastery\src\index.ts:246:24)
                            at property (D:\dev\genshin-bot\node_modules\.pnpm\schemastery@3.6.1\node_modules\schemastery\src\index.ts:357:35)
                            at <anonymous> (D:\dev\genshin-bot\node_modules\.pnpm\schemastery@3.6.1\node_modules\schemastery\src\index.ts:405:19)
                            at Function.resolve (D:\dev\genshin-bot\node_modules\.pnpm\schemastery@3.6.1\node_modules\schemastery\src\index.ts:246:24)
                            at schema (D:\dev\genshin-bot\node_modules\.pnpm\schemastery@3.6.1\node_modules\schemastery\src\index.ts:92:19)
                            at resolveConfig (D:\dev\genshin-bot\node_modules\.pnpm\cordis@2.7.1\node_modules\cordis\src\utils.ts:19:54)
                            at Registry.plugin (D:\dev\genshin-bot\node_modules\.pnpm\cordis@2.7.1\node_modules\cordis\src\registry.ts:100:14)
                            at Context.<anonymous> (D:\dev\genshin-bot\node_modules\.pnpm\cordis@2.7.1\node_modules\cordis\src\context.ts:78:27)
                            at Context.import_core.Context.plugin (D:\dev\genshin-bot\node_modules\.pnpm\koishi@4.11.3\node_modules\koishi\src\index.ts:36:17)
```

### Steps to reproduce

给插件添加Date类型的配置项
```typescript
export interface Config {
  date: Date
}
export default class TestPlugin {
  static Config = Schema.object({
    test: Schema.date().description('时间')
  })

  // constructor...
}
```
修改配置文件koishi.yml
```yaml
plugins:
  group:dev:
    test:
      test: 2001-12-15T02:59:43.1Z
```
BTW， 如果从控制台输入日期时间并保存配置，保存的是以下格式
![image](https://user-images.githubusercontent.com/21982381/214810656-6ba47179-8b40-44d6-a7b4-0a608e9646bf.png)

然后运行koishi（已配置为启用该插件） `pnpm run dev`，出现报错，插件无法运行

![image](https://user-images.githubusercontent.com/21982381/214814384-ff715891-2da5-41c0-8679-7ec39ff85ca1.png)

### Expected behavior

顺利运行插件

### Versions

- Koishi version: 4.11.3
- schemastery: 3.6.1

**Comment by shigma** [comment]
目前建议用户写 `Schema.string().role('date')` 替代 `Schema.date()`。

文档：https://shigma.github.io/schemastery/atomic/date.html
