### ISSUE TITLE
Bug: OneBot能在频道发送视频吗

### ISSUE THREAD

**Issue by 15015070064** [koishijs/koishi#962]
### Describe the bug

使用onebot往频道发送视频，报错
```
2023-02-04 10:40:43 [W] gocqhttp Protocol -> device lock is disable. http api may fail.
2023-02-04 10:41:05 [W] gocqhttp 转换CQ码 ({"type":"video","data":{"file":"file:///root/kuroshio-bot/plugins/kuroshio-genshin-plugin/src/plugins/xiaoyao-plugin/resources/xiaoyao-plus/basicInfo_tujian/role/芭芭拉/芭芭拉.mp4"}}) 到MiraiGo Element时出现错误: extract video cover failed: exec: "ffmpeg": executable file not found in $PATH 将忽略本段CQ码.
2023-02-04 10:41:05 [W] gocqhttp 频道消息发送失败: 消息为空.
2023-02-04 10:41:05 [W] session Error: Error with request send_guild_channel_msg, args: {"guild_id":"90669671661153134","channel_id":"10295597","message":[{"type":"video","data":{"file":"file:///root/kuroshio-bot/plugins/kuroshio-genshin-plugin/src/plugins/xiaoyao-plugin/resources/xiaoyao-plus/basicInfo_tujian/role/芭芭拉/芭芭拉.mp4"}}]}, retcode: 100
                            at _Internal._get (/root/kuroshio-bot/node_modules/@satorijs/adapter-onebot/src/types.ts:546:11)
                            at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at _Internal._Internal.<computed> (/root/kuroshio-bot/node_modules/@satorijs/adapter-onebot/src/types.ts:583:20)
                            at OneBotMessenger.flush (/root/kuroshio-bot/node_modules/@satorijs/adapter-onebot/src/bot/message.ts:63:14)
                            at OneBotMessenger.send (/root/kuroshio-bot/node_modules/@satorijs/core/src/message.ts:45:5)
                            at send_Msg (/root/kuroshio-bot/plugins/kuroshio-genshin-plugin/src/plugins/xiaoyao-plugin/apps/xiaoyao_image.js:163:23)


```

### Steps to reproduce

1. 安装ffmpeg
```
apt install -y ffmpeg
```
2. 检查是否安装成功
```
ffmpeg -version
echo $PATH
```
3. 配置onebot
4. 往频道发送视频

### Expected behavior

onebot是否支持发送视频

### Versions

- OS: ubuntu 18
- Platform: QQ Guild
- Node version: 17
- Koishi version: 4.11.4

**Comment by shigma** [comment]
你没有安装 FFmpeg。请自行安装：

https://koishi.chat/plugins/adapter/onebot.html#%E5%AE%89%E8%A3%85-ffmpeg

**Comment by shigma** [comment]
抱歉之前看错了，把 ffmpeg 看成你的报错信息了。

我去了解一下频道能不能发视频。

**Comment by 15015070064** [comment]
> 抱歉之前看错了，把 ffmpeg 看成你的报错信息了。
> 
> 我去了解一下频道能不能发视频。

我看了文档，说是可以发语音，但是不能说能不能发视频

**Comment by shigma** [comment]
> executable file not found in $PATH

你确定你装进 path 了吗？

**Comment by shigma** [comment]
另，如果运行着 gocq 的时候安装 ffmpeg 是不行的，你得退出重开。

**Comment by 15015070064** [comment]
> 另，如果运行着 gocq 的时候安装 ffmpeg 是不行的，你得退出重开。

我又重新装了一次，并且重写打开console，我确定ffmpeg被安装在 /usr/bin
```
root@genshin:~/kuroshio-bot# whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /usr/share/man/man1/ffmpeg.1.gz
```
我的$PATH是这样的，按道理应该已经包含了/usr/bin
```
/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by 15015070064** [comment]
> 抱歉之前看错了，把 ffmpeg 看成你的报错信息了。
> 
> 我去了解一下频道能不能发视频。

在windows下测试过，可以发视频。生产环境是ubuntu，估计是需要配置点东西

**Comment by MaikoTan** [comment]
I have noticed that you are logged in as `root`, since `$PATH` and other environment variable would be relative to the user that running the command. You might need to make sure it is still in `$PATH` when you're running Koishi or `go-cqhttp`.

我注意到你登錄為`根`，自從`$PATH`和其他環境變數會和運行指令的使用者相關。你可能需要確認當你運行戀石或`go-cqhttp`的時候它仍在`$路徑`中。

**Comment by Willyoucallme** [comment]
> I have noticed that you are logged in as `root`, since `$PATH` and other environment variable would be relative to the user that running the command. You might need to make sure it is still in `$PATH` when you're running Koishi or `go-cqhttp`.
> 
> 我注意到你登錄為`根`，自從`$PATH`和其他環境變數會和運行指令的使用者相關。你可能需要確認當你運行戀石或`go-cqhttp`的時候它仍在`$路徑`中。

我切换了用户，并且通过一些方法在运行koishi的时候把$PATH打印出来，如下所示
![image](https://user-images.githubusercontent.com/40047545/216755981-e97865b6-a149-4745-8f49-e207c38ae720.png)

我尝试了下面两种方法，都失败了，错误代码都是一样
1. 把ffmpeg放入/usr/local/games
![image](https://user-images.githubusercontent.com/40047545/216756017-d3943e69-64b3-4ac3-9641-daf78d8dd083.png)

2. 在node_module下面建立软链接
![image](https://user-images.githubusercontent.com/40047545/216756038-62e71872-7941-4843-9f92-681ec503db94.png)

**Comment by MaikoTan** [comment]
As this issue was beyond the scope that Koishi Team could deal with, I would convert this issue to be a discussion. And then we could talk there.
