### ISSUE TITLE
 连接至go-cqhttp后报错

### ISSUE THREAD

**Issue by fatinghenji** [koishijs/koishi#982]
```
2023-02-15 07:55:47 [W] onebot TypeError: Cannot read properties of undefined (reading 'replace')
                            at Function.escape (/home/koishi-app/node_modules/@satorijs/element/lib/index.cjs:101:27)
                            at ElementConstructor.toString (/home/koishi-app/node_modules/@satorijs/element/lib/index.cjs:37:51)
                            at Array.join (<anonymous>)
                            at adaptMessage (/home/koishi-app/node_modules/@satorijs/adapter-onebot/lib/index.js:315:36)
                            at OneBotBot.getMessage (/home/koishi-app/node_modules/@satorijs/adapter-onebot/lib/index.js:804:18)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async adaptMessage (/home/koishi-app/node_modules/@satorijs/adapter-onebot/lib/index.js:310:20)
                            at async adaptSession (/home/koishi-app/node_modules/@satorijs/adapter-onebot/lib/index.js:368:5)
                            at async dispatchSession (/home/koishi-app/node_modules/@satorijs/adapter-onebot/lib/index.js:355:19)
2023-02-15 07:55:47 [W] app TypeError: Cannot read properties of undefined (reading 'replace')
                            at Function.escape (/home/koishi-app/node_modules/@satorijs/element/lib/index.cjs:101:27)
                            at ElementConstructor.toString (/home/koishi-app/node_modules/@satorijs/element/lib/index.cjs:37:51)
                            at Array.join (<anonymous>)
                            at adaptMessage (/home/koishi-app/node_modules/@satorijs/adapter-onebot/lib/index.js:315:36)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async adaptSession (/home/koishi-app/node_modules/@satorijs/adapter-onebot/lib/index.js:368:5)
                            at async dispatchSession (/home/koishi-app/node_modules/@satorijs/adapter-onebot/lib/index.js:355:19)\
```
上面还有一个插件市场的报错，不清楚是否与改问题相关：
```
023-02-15 07:47:35 [I] market ➤ YN0050: The --registry option is deprecated; prefer setting npmRegistryServer in your .yarnrc.yml file
2023-02-15 07:47:36 [I] market ➤ YN0000: ┌ Resolution step
2023-02-15 07:47:36 [I] market ➤ YN0002: │ @koishijs/plugin-adapter-discord@npm:3.5.1 [dd020] doesn't provide @satorijs/satori (p18fed), requested by @satorijs/adapter-discord
2023-02-15 07:47:36 [I] market ➤ YN0002: │ @koishijs/plugin-adapter-feishu@npm:1.1.3 [dd020] doesn't provide @satorijs/satori (p46e79), requested by @satorijs/adapter-feishu
2023-02-15 07:47:36 [I] market ➤ YN0002: │ @koishijs/plugin-adapter-kook@npm:3.5.2 [dd020] doesn't provide @satorijs/satori (pf945b), requested by @satorijs/adapter-kook
2023-02-15 07:47:36 [I] market ➤ YN0002: │ @koishijs/plugin-adapter-onebot@npm:5.5.4 [dd020] doesn't provide @satorijs/satori (p1efbc), requested by @satorijs/adapter-onebot
2023-02-15 07:47:36 [I] market ➤ YN0002: │ @koishijs/plugin-adapter-telegram@npm:3.6.7 [dd020] doesn't provide @satorijs/satori (pdbbd8), requested by @satorijs/adapter-telegram
2023-02-15 07:47:36 [I] market ➤ YN0002: │ @koishijs/plugin-database-sqlite@npm:3.3.2 [dd020] doesn't provide @minatojs/core (pec853), requested by @minatojs/driver-sqlite
2023-02-15 07:47:36 [I] market ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
2023-02-15 07:47:36 [I] market ➤ YN0000: └ Completed in 0s 454ms
2023-02-15 07:47:36 [I] market ➤ YN0000: ┌ Fetch step
2023-02-15 07:47:36 [I] market ➤ YN0013: │ @koishijs/plugin-echo@npm:2.0.6 can't be found in the cache and will be fetched from the remote registry
2023-02-15 07:47:36 [I] market ➤ YN0000: └ Completed in 0s 397ms
2023-02-15 07:47:36 [I] market ➤ YN0000: ┌ Link step
2023-02-15 07:47:37 [I] market ➤ YN0000: └ Completed in 0s 261ms
2023-02-15 07:47:37 [I] market ➤ YN0000: Done with warnings in 1s 189ms
```

**Comment by shigma** [comment]
此问题已修复。@koishijs/plugin-adapter-onebot 刚刚发布了 5.5.5 版本。
